### ISSUE TITLE
Lite not starting when executed from command-line outside of its own directory (Ubuntu 19.10)

### ISSUE THREAD

**Issue by benit8** [rxi/lite#1]
I use Ubuntu 19.10, Linux 5.3.0-24-generic

After cloning and building Lite without any problem, I moved its directory to my `/opt/`. I created a symlink to the binary in my `/usr/sbin/` to use Lite globally. But once launched in any directory that is not its own (in my case `/opt/lite/`), it prints out this error and exits:

```
Error: [string "local core..."]:7: attempt to concatenate global '_EXEDIR' (a nil value)
stack traceback:
	[string "local core..."]:7: in function <[string "local core..."]:2>
	[C]: in function 'xpcall'
	[string "local core..."]:2: in main chunk
```

I fixed it by adding my own path to the Lua string in `src/main.c`, line 66, as follows:
```lua
_EXEDIR = _ARGS[1]:match('(.*)[/\\\\].*$') or '/opt/lite'
```
After recompiling, it launched perfectly fine.
But of course this edit only works for me.

As I understand it, you need to access the `data/` directory where the Lua scripts are located. Why not have an installation script that saves into a user config file where the sources are?
Also, I guess I need to write in `data/user/init.lua` if I want to customize Lite's behavior, but what about having a `.literc` file or `.lite` directory in the user's home?

Thank you for your time and work on this project :)

**Comment by rxi** [comment]
The problem regarding `_EXEDIR` not being set to the correct value is definitely something I plan to fix. In regard to the other issue of the user settings being kept in the `data` directory: for the sake of simplicity, this will probably be kept the way it is for the time being, thus in its current state the program is expected to be installed per-user.

Thanks for taking the time to make an issue!

**Comment by monolifed** [comment]
As a workaround, I used a proxy script (e.g. lite.sh) in the same folder as lite:
```sh
#!/bin/sh
LITE_DIR="$(dirname "$(readlink -f "$0")")"
exec "$LITE_DIR/lite" "$@"
```
then I symlinked the script as lite (rather than lite itself)

**Comment by Nullious** [comment]
Same Issue in windows. Will try your suggested fix.

**Comment by Nullious** [comment]
Same issue on windows.

**Comment by rxi** [comment]
It should hopefully be working properly now. @Nullious would you be able to confirm whether this fixes the issue for you on windows? Thanks!

**Comment by intxparts** [comment]
The issue on Windows was also resolved. Thanks @rxi !
