### ISSUE TITLE
Saving a new file doesn't create file in opened project

### ISSUE THREAD

**Issue by mundusnine** [rxi/lite#100]
When creating a new file and saving it(with ctrl+s), the file doesn't save at project root even if we specify the path to be `.\mytest.txt` as it seems to take the `.` path of the executable.

**Comment by Gavin-Holt** [comment]
Hi

I can reproduce (and fix) this on Windows 10 with Lite 1.03. 

It appears that when Windows makes a shortcut it will default to adding the lite.exe directory as the "Start in" directory. This then becomes the project directory regardless of opening a file from another location. 

To prevent this any shortcut to Lite should have a blank "Start in" field in the shortcut definition. Please note your Quicklauch and Pinned Items are all shortcuts.

![Shortcut to Lite exe](https://user-images.githubusercontent.com/5831149/82117948-bb6d0380-976b-11ea-9897-c5629d9e8223.png)

Alternatively placing Lite.exe, or a batch file calling Lite.exe in the path allows easy launching from the command line.

Kind Regards Gavin Holt
