### ISSUE TITLE
Add possibility to quit editor forcefully with RC != 0

### ISSUE THREAD

**Issue by Anachron** [rxi/lite#106]
I'm on linux and editors like vim allow the user to exit with a non-zero RC. 

My scripts have been written in a way that if an editor exists with `RC != 0` the file will be deleted, otherwise the user wants to continue.

Can this be implemented in the current "Force Quit"?

**Comment by rxi** [comment]
Though not something I want to introduce as a command in the core, this could be trivially added as a command in your user module:
```lua
local command = require "core.command"
command.add(nil, { ["user:quit-error"] = function() os.exit(1) end })
```

**Comment by Anachron** [comment]
Sounds good! Closing.
