### ISSUE TITLE
Add Arch Linux AUR package

### ISSUE THREAD

**Issue by klorophatu** [rxi/lite#107]

**Comment by talentlessguy** [comment]
I'd recommend starting from this:

```shell
pkgname=lite-bin
pkgver=1.0.0
pkgrel=1
pkgdesc="program desc"
arch=('x86_64')
url="https://github.com/rxi/lite"
license=('GPL3')
provides=('lite-bin')

source_x86_64=("https://github.com/rxi/lite/releases/download/v${pkgver}/lite-${pkgver}")
noextract=("lite-${pkgver}")
sha256sums_x86_64=('hexblahblah')

package () {
  install -Dm 775 "program-${pkgver}" "${pkgdir}/usr/bin/lite"
}
```

**Comment by rxi** [comment]
This isn't something I plan to support myself -- anyone is welcome to take on the task themselves with each release.

**Comment by WingofaGriffin** [comment]
For reference, it appears somebody took the initiative here: https://aur.archlinux.org/packages/lite/

Might be worth adding to the readme as "unofficial" installations for distros, though I haven't check any of the other popular ones for their packages.
