### ISSUE TITLE
Use System fonts by default?

### ISSUE THREAD

**Issue by Anachron** [rxi/lite#108]
Right now fonts are declared in `style.lua` like:

```lua
style.font = renderer.font.load(EXEDIR .. "/data/fonts/font.ttf", 14 * SCALE)
style.big_font = renderer.font.load(EXEDIR .. "/data/fonts/font.ttf", 34 * SCALE)
style.icon_font = renderer.font.load(EXEDIR .. "/data/fonts/icons.ttf", 14 * SCALE)
style.code_font = renderer.font.load(EXEDIR .. "/data/fonts/monospace.ttf", 13.5 * SCALE)
```

Wouldn't it be good if it defaults to my (monospace) system font (and size) by default?

**Comment by Anachron** [comment]
I mean I can manually specify it like

```
local HOMEDIR = os.getenv("HOME")

style.code_font = renderer.font.load(HOMEDIR .. "/.fonts/Hack-Regular.ttf", 13.5 * SCALE)
```

But I would have to do that every time I update my system font.

**Comment by rxi** [comment]
This isn't something I plan to change in the core, such that `lite` retains the same look, per-pixel, across all platforms.

That being said I believe you can use the following command with `io.popen` to get your system's default monospace font:
```bash
fc-match --format="%{file}" mono
```

**Comment by Anachron** [comment]
@rxi yep, I took a bit different approach (reading xrdb and then retrieving the `ttf` path), your solution is much simpler! Thanks.
