### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Dmunch04** [rxi/lite#114]
Hi. I can't seem to run it. I keep getting the same error. How would I fix this error:
```
munchii@pop-os:~/Downloads/Lite$ ./lite
./lite: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by rxi** [comment]
You need to install `libsdl2` from your package manager. If it still doesn't work you need to install `libsdl2` dev libraries from your package manager and run the `build.sh` script
