### ISSUE TITLE
Separate releases for each platform

### ISSUE THREAD

**Issue by talentlessguy** [rxi/lite#116]
Instead of downloading all of the platforms, I think it would be wiser to ship each release for a different platform in a different file.

Example: https://github.com/kitze/twizzle/releases/tag/v1.2.5

![image](https://user-images.githubusercontent.com/35937217/82740925-df28de80-9d55-11ea-9057-12eef17e5ce0.png)

**Comment by rxi** [comment]
This seems unnecessary given the release builds only target two platforms, and the resultant zip file is one 50th the size of any of the ones listed on your example.

**Comment by ur4ltz** [comment]
No, you need it! Why do I need a Linux exe file for windows!.

**Comment by talentlessguy** [comment]
@rxi well why do I need to pull exe if I use it on Linux? Also, it blocks https://github.com/rxi/lite/issues/107, because the release we download should contain only the executable file for Linux.
