### ISSUE TITLE
Avoid loading default starting folder (home) when not run from console

### ISSUE THREAD

**Issue by sepisoad** [rxi/lite#117]
I open lite from gnome launcher and It loads my home folder and It take a long time for it to fully load and parse the whole home folder.

I think it is nice to prevent Lite from loading a default path when it is not given any path.

**Comment by rxi** [comment]
At least for the moment, I've changed lite to always start with its own directory as the project directory if not provided with one, as it's currently always expected to have a project directory set. This prevents the issue where it would scan your whole home directory in the case it was launched from there with no directory set.

7517d0ef552c89cc24e0589a8df8eb9648217e24
