### ISSUE TITLE
can't open project folder out of lite root directory

### ISSUE THREAD

**Issue by boris-741** [rxi/lite#12]
OS Win 10 64bit
put lite in c:\lite and open c:\project dir from lite

**Comment by LaineZ** [comment]
same problem, also if you run from cmd like ``lite.exe c:/path/to/folder`` editor crashes...

**Comment by rxi** [comment]
I can't manage to reproduce this, also Windows 10 64bit:

![screenshot](https://user-images.githubusercontent.com/3920290/79638842-9f337200-817f-11ea-9d53-58a35d5fb50b.png)

Could you provide more details of what actually happens? `lite` should produce an `error.txt` file next to the .exe if it crashes, would you be able to paste the content of this file here if it was produced?
