### ISSUE TITLE
Cannot open doc on locked node

### ISSUE THREAD

**Issue by maacl** [rxi/lite#120]
I get the above for any doc I try to open. Using latest release on Ubuntu 20.04

**Comment by rxi** [comment]
If you try to open a document when the active view's node is a locked node, and the previously active view's node is also a locked node, lite will be unable to open it -- locked nodes by default are the statusbar, commandview and treeview. Clicking the view of a non-locked node (eg, an open doc or empty view) and then opening a doc would work.

Currently this is intended behaviour but may change in the future if there is a change to the way views are handled.

**Comment by maacl** [comment]
I am sorry but I don't understand this. I do CTRL-O and the result is the above for any file I pick. Is this the intended behaviour?

**Comment by rxi** [comment]
If this happens when opening lite, having not clicked anything or done anything else besides pressing `ctrl+o`, then in that case: no, it is not intended behaviour. 

On a fresh copy of lite this is not something I'm able to reproduce

**Comment by maacl** [comment]
Oh, I think I see what you mean. Sorry for the confusion.
