### ISSUE TITLE
Blocks compositing on KDE

### ISSUE THREAD

**Issue by StarrKiss** [rxi/lite#123]
When using this by default in KDE, it blocks the compositing of windows/disables the compositor. This is really annoying, but can be undone with a window rule manually. Just something that would be useful.

**Comment by rxi** [comment]
Do you experience this with other SDL2 applications? I'm unsure if this is something that should be fixed in lite or if it is an issue with SDL2

**Comment by dslul** [comment]
@rxi by default, every sdl application (usually games) tell the system to disable compositing (see this https://github.com/rxi/lite/blob/d8c4bfa6bad7153486fd68f8c9368dc3bb458ce5/winlib/SDL2-2.0.10/x86_64-w64-mingw32/include/SDL2/SDL_hints.h#L221). Of course, an editor should not, so I sent a pull request :)
