### ISSUE TITLE
Zooming text in and out

### ISSUE THREAD

**Issue by 6r1d** [rxi/lite#129]
Hello. I'd like to be able to change text size and I tried adding this functionality myself, but I'm not sure what I am doing wrong.
(I'd like to have `ctrl +` / `ctrl -`/ `ctrl 0` to change font size, as well as `ctrl scroll`)

Can anyone have a look at [my gist](https://gist.github.com/6r1d/cbda84c5acbd11ba53a6cb3a6b4d0008) and tell me what I'm breaking? Also I'm not sure how to even add ctrl+scroll.

Thanks!

**Comment by rxi** [comment]
All keymaps map to commands which should be added through the command system:
```lua
local command = require "core.command"

command.add(nil,  {
  ["user:zoom-in"] = function()
    style.fscale = (1 + style.fscale) * 1.1
    style.set_font()    
  end,
  ["user:zoom-out"] = function()
    style.fscale = (1 + style.fscale) * 0.9
    style.set_font()    
  end,
  -- ...
})
```

Note this is functionality that should be added in your user module or as a plugin rather than something that the core should be modified directly for:

```lua
local style = require "core.style"
local command = require "core.command"
local keymap = require "core.command"

-- ...

keymap.add {
  ["ctrl+="] = "user:zoom-in",
  ["ctrl+-"] = "user:zoom-out",
}
```

**Comment by 6r1d** [comment]
> Note this is functionality that should be added in your user module or as a plugin

Is it alright to have this plugin as a default one? I want to change font size from time to time, since my eyesight is not that good.

If yes, I'll add a PR for [this branch](https://github.com/6r1d/lite/tree/text_zoom).

By the way, will it be possible to create mixed keybindings like `ctrl + mouse scroll up`?

**Comment by rxi** [comment]
Unfortunately this approach breaks custom styling set from the user module, given this I'm hesitant that even having it as a public plugin in the plugins repo is a good idea, at least in its current form; there are some changes that could be made to improve it, eg. tracking font filenames/sizes by overriding `renderer.font.load()`, and only ever changing size values relative to their current value instead of absolutely, such that non-default sizes work as expected.

Regarding `ctrl+mouse scroll up`, the keymap only supports keyboard input; for handling this you would have to override the `on_wheel_scroll()` function and check `keymap.modkeys["ctrl"]` to see if ctrl is down. See the `autoreload.lua` file for an example of how to override functions.

**Comment by hugows** [comment]
Love this feature @6r1d ! Like you, sometimes my eyesight is super crisp and other times of the day not so good. Since you're more into lite than me, do you know if its possible to not resize the treeview? It gets ugly fast.

**Comment by 6r1d** [comment]
> breaks custom styling set from the user module

Let's discuss what can be fixed. I believe this feature has a potential.

> there are some changes that could be made to improve it, eg. tracking font filenames/sizes

I'd like to know more. As far as I understand now, fonts are rasterized using [stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h), right?
Do you propose saving font filename and rasterized size to a global variable to avoid artifacts later? 
Or should there be some other approach (re-rasterization / caching / etc.)?

> and only ever changing size values relative to their current value instead of absolutely, such that non-default sizes work as expected

Is that related to a rasterization process, too?

In your code, you wrote `(1 + style.fscale) * 1.1` and in both cases there was this part `(1 + style.fscale)`, so font size was always incremented.

Is that alright to use `style.fscale * 1.05` and `style.fscale * 0.95` instead?

> for handling this you would have to override the on_mouse_wheel() function

Thanks, I will look into this after I'll be able to fix basics.

---

> do you know if its possible to not resize the treeview

Well, we are discussing how to approach this issue, I did not make any good solution yet. :-)

For now, you can try to customize `style.lua`: while I moved `style.font`, `style.big_font`, `style.icon_font`, `style.code_font` inside `style.set_font` function, you can cut and paste one of these definitions above and test.

I think it won't be `style.code_font` or `style.big_font`, but I have not tried that yet.

**Comment by rxi** [comment]
I've implemented and pushed a `scale` plugin to the plugins repo, this implementation should work correctly with custom style configurations and fonts; if you want support for mouse wheel scrolling this will have to be added to your user configuration using the method I described above:

https://github.com/rxi/lite-plugins/blob/master/plugins/scale.lua
