### ISSUE TITLE
Numpad enter key does not work

### ISSUE THREAD

**Issue by 6r1d** [rxi/lite#131]
Enter key is working in other programs well, primary enter key is working, too.

OS: Ubuntu 18.04.4 LTS.
Computer: Lenovo Ideapad 330S-15ARR.

**Comment by rxi** [comment]
Could you add `print(k)` to the top of the `keymap.on_key_pressed(k)` function in `data/core/keymap.lua` and let me know what it prints when you press the enter? Lite only has mappings for the return key as opposed to the numerical-pad-enter key which presumably has a different name.

**Comment by 6r1d** [comment]
It was 'keypad enter'. I fixed it and added a PR.
Thanks a lot, I like Lite more and more.

**Comment by rxi** [comment]
Fixed by #133
