### ISSUE TITLE
suggestion: Two repo's - c-code 'exe' repo, and Lua-code 'app' repo

### ISSUE THREAD

**Issue by wallabyway** [rxi/lite#140]
Separate code into two GitHub repo's ... 

1. a repo for the exe (ie. the "bootstrap")... 
2. and a repo for the Lua code (ie. the application) 

Might make the Mac builds a bit easier to manage.

Also means you could easily add an 'auto-update' feature, by hosting the raw Lua code on GitHub pages.

**Comment by rxi** [comment]
This goes against the general goal of simplicity for lite and is not something that will be done. Regarding making "mac builds a bit easier to manage" I've already [suggested a solution](https://github.com/rxi/lite/issues/104#issuecomment-634549366).
