### ISSUE TITLE
Quality of Life changes

### ISSUE THREAD

**Issue by TorchedSammy** [rxi/lite#141]
Here are some quality of life suggestions to make Lite a little bit easier to use. If someone else can make these in plugins too that would be nice

- Right click menu on treeview
Give us a right click menu for the treeview, where right clicking the empty treeview or a file/folder gives us a menu to do things like deleting and creating files/folders, renaming, moving etc.
- Open folder in editor
An easy way to open a new project folder would be in the editor itself like with a keybind opening a folder selector of the os.
- Launching the executable opening the last opened workspace folder (so EXEDIR but not the actual executed directory and instead a specific folder..?)

**Comment by TorchedSammy** [comment]
bump. also, hot reloading the lua files for the app

**Comment by mateusmds** [comment]
There is a plug-in to open the last project opened. Also in Linux (I don't know how to do it in Windows or Mac) you can give the Laucher the argument "%F", that will open grag-dropped folders in the icon
