### ISSUE TITLE
.editorconfig support 

### ISSUE THREAD

**Issue by Tmpod** [rxi/lite#142]
Hi!
`.editorconfig` is a nice "standardised" way of specifying some configurations across all editors that support it. This is a neat tool to use in big projects with lots of contributorsa and it would be cool to have in lite too, if not on the core, at least as a plugin. 

You can read more about `.editorconfig` at https://editorconfig.org

**Comment by rxi** [comment]
This isn't something I'm going to add myself, nor something I'm going to introduce into core lite. It should be fairly trivial for anyone who wants this functionality to write this as a plugin and submit it to the plugins repo though!

**Comment by Tmpod** [comment]
I see, I need to get into Lua, this editor is very cool!   
Should I close the issue or leave it open as a TODO for someone else? 😄

**Comment by rxi** [comment]
It might make more sense to move these kinds of issues over to the `lite-plugins` repo and we can tag it as `plugin request` or something if you want to close it and make it there instead.

**Comment by Tmpod** [comment]
Sure thing! Will do that now :)

**Comment by Tmpod** [comment]
Btw, I know this isn't the right place to ask, but is there any other platform I could contact you? Maybe a more chat oriented one.

**Comment by rxi** [comment]
I can add you on discord if you let me know your name on there, the one on your site didn't work

**Comment by Tmpod** [comment]
> I can add you on discord if you let me know your name on there, the one on your site didn't work

Oh true, my Nitro just reset so my discriminator has been randomised. I need to update my page.
My current username is Tmpod#2525
