### ISSUE TITLE
Add nim syntax highlighting?

### ISSUE THREAD

**Issue by gsbhasin123** [rxi/lite#146]
From https://nim-lang.org/ (it's a great language):
>  Nim is a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula.

**Comment by rxi** [comment]
This won't be added to the core but would make a welcome addition to the [plugins repo](https://github.com/rxi/lite-plugins). If anyone familiar with nim wants to take a stab at writing a syntax plugin for it, the `language_python` plugin in core might be a good place to start!

**Comment by gsbhasin123** [comment]
Thanks! I'll take a stab at making one, but just curious, why will it not be added to the core? Also, I can't find language_python.lua in https://github.com/rxi/lite-plugins/tree/master/plugins.

**Comment by rxi** [comment]
[`language_python` is part of the main repo](https://github.com/rxi/lite/blob/master/data/plugins/language_python.lua)

> why will it not be added to the core?

Only a handful of plugins are included with lite, as to keep in line with its goal of staying lightweight

**Comment by gsbhasin123** [comment]
Thanks for the responses!
