### ISSUE TITLE
Strict-aliasing violation in `Command` allocations

### ISSUE THREAD

**Issue by integricho** [rxi/lite#148]
Hi! First of all, kudos to this project, it's beautifully designed, really nice ideas!

I've been skimming over the implementation of the core part, while reading your design rationale, and noticed that commands are allocated from a `static char` array, which violates the strict aliasing rules.

The offending code is here, first reinterpreting a memory region of the `char` array as a `Command` pointer:
https://github.com/rxi/lite/blob/ba6c14846b97512254901357392d5a649fe130dd/src/rencache.c#L80

And the violation happens on the first access, writing the `int` to the memory location:
https://github.com/rxi/lite/blob/ba6c14846b97512254901357392d5a649fe130dd/src/rencache.c#L88

**Comment by JesseRMeyer** [comment]
Does the static qualifier on the char buffer enforce strict aliasing semantics?  I thought char pointers were always assumed to be aliased by the compiled -- to allow for this use case.

**Comment by integricho** [comment]
AFAIK `static` has no effect on the enforcement of the strict aliasing rules, it's enforced regardless. Otherwise you are correct, `char` pointers are allowed to alias any region of memory, but they're allowed to be used only for:
- viewing the raw bytes of a type (e.g. serialization): casts, `union`, `memcpy` are all allowed techniques in C, while C++ allows only casts and `memcpy`
- or to reconstruct a type from it's raw bytes (e.g. deserialization): only `union`s and `memcpy` are allowed in C, while C++ allows only `memcpy` for this (although compilers at this time still generate correct code even for C++ `union` hacks)

However, using a `char` array to back live objects of other types is not allowed unfortunately.

**Comment by JesseRMeyer** [comment]
If that is true, then how are C allocators permitted to back live objects?  Surely not a unique function per type to be allocated.

**Comment by integricho** [comment]
Yes I think you're reasoning is correct, this is strictly :) a spec violation, at this point no actual bug exists (at least none that I'm aware of). There's just the possibility that future changes in the code might lead to a situation where this becomes important. I apologize if my issue sounded alarming or anything like that :)

As for C-allocators, they deal in `void` which are explicitly allowed by the spec to be reinterpreted however needed, but I guess my wording is also poor regarding that point, the strict aliasing rules only affect the actual reads / writes, doesn't really care about what backs what.

**Comment by JesseRMeyer** [comment]
Thanks for explaining. :)

**Comment by integricho** [comment]
Thanks for the conversation :)

**Comment by rxi** [comment]
Is there a practical way of achieving what the code does *without* violating strict aliasing? Otherwise I assume changing the build script to compile with `-fno-strict-aliasing` would prevent any potential issues

**Comment by integricho** [comment]
Yes, disabling optimizations related to strict aliasing would certainly allow the code to remain as-is, and if these optimizations are not crucial for `lite`, I guess that's the most convenient solution.

Otherwise I think the code could be restructured in a way (but I might have overlooked something else, please correct me), for example with these changes:

1. Switching the zero-length array member of the `Command` type to a pointer+size pair (or index+size), making the struct's size a constant
2. Changing `command_buf`'s type to be an actual array of `Command` objects
3. Introducing another `char` array for the text data only.

This way, `Command` objects could point into this other `char` array, with the pointer+size pair, denoting the text data itself. Allocations and deallocations would happen in pair (in both `Command` and `char` array) for text commands.

One downside of this would certainly be the constant increase in the size of `Command` instances, as the pointer+size members would always take up some space.

**Comment by rxi** [comment]
For the sake of code simplicity and retaining the current behaviour I've added the `-fno-strict-aliasing` flag to the build script and will consider this resolved.

That being said I really appreciate the time you put in to outlining an alternate solution to the problem @integricho; using two arrays isn't something I had considered and is definitely helpful if this turns out to be something that does need changing in the future. 

Thanks!

**Comment by JesseRMeyer** [comment]
An alternative approach that includes -fno-strict-aliasing may be to qualify the cmd pointer as restricted.  See: https://en.wikipedia.org/wiki/Restrict

This qualifier tells the compiler, and signals to readers, "I promise that access to the underlying data will only happen through this (or derived) pointer."  In practice this often means "I am willfully violating strict aliasing semantics, but have determined there to be no actual bugs."  So with the aliasing optimizations disabled, this qualifier re-enables that optimization on this particular pointer.

```c
Command *restrict cmd = (Command*) (command_buf + command_buf_idx); 
```
