### ISSUE TITLE
Multicursor support 

### ISSUE THREAD

**Issue by Tmpod** [rxi/lite#150]
This editor is really nice and clearly inspired by SublimeText (by various features and keybinds), however one crucial feature is missing: multicursors. The ability to select multiple regions of a file and change the all at the samettime is insanely powerful and handy and implementing it would make lite even more viable as a daily driver.

**Comment by rxi** [comment]
This isn't something that will be added to `lite`, the reason as always is simplicity. Lite was designed intentionally *not* to have this feature, that is, supporting this *properly* would have been a conscious choice from the beginning and would have influenced many other decisions from there-on-out -- from how documents are stored, to how positions are specified, to how plugins are written, to how every command is implemented.

That being said, though this won't be a feature of lite, there is a lite-related project in development which will support this feature.

**Comment by edubart** [comment]
I've been trying out lite because I loved the philosophy behind it and as a Sublime Text user too this feature is what I miss the most. @rxi What lite-related project does support this feature?

**Comment by rxi** [comment]
@edubart https://twitter.com/martin_cohen/status/1263749159942787072

**Comment by AqilCont** [comment]
Can we find the repository and/or app anywhere? I don't see it posted on the dev's website at all, and their Github profile just shows a bunch of projects under development(some over 2 years old o_O).
