### ISSUE TITLE
Bug introduced in commit 7517d0e

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite#152]
@rxi As you have suggested in https://github.com/rxi/lite/commit/7517d0ef552c89cc24e0589a8df8eb9648217e24, here is a gif with my current `EXEDIR` issue:

![output](https://user-images.githubusercontent.com/1777466/84569571-6afbbc80-ad90-11ea-9a46-d6141cd2d31e.gif)

**Comment by rxi** [comment]
From the look of the gif I'm guessing you've wrapped `lite` in a shell script which you aren't properly propagating the command line arguments to

**Comment by stefanos82** [comment]
Yes, this is my script:

```bash
#!/bin/sh

(/PortableApps/lite/lite & >/dev/null &)
```

**Comment by rxi** [comment]
This is a fault in your script, not in lite's behaviour. The arguments you're passing to your script aren't being passed to lite.

**Comment by stefanos82** [comment]
Yes, I have updated my script to run a series of arguments, but seems there's an issue with single file loading.

It loaded the file correctly, but for some reason it displays `EXEDIR`s contents.

![image](https://user-images.githubusercontent.com/1777466/84570711-dac17580-ad97-11ea-96ec-25b0a0a4d6e5.png)

**Comment by rxi** [comment]
This is the new intended behaviour to prevent situations where lite is opened in a upper-level directory (eg. your home directory or root) when editing a single file which -- in the worst case -- would cause lite to create an internal list of every file on your system, as it would consider root the project directory.

To mimic lite's old behaviour you should pass it `.` as an argument. This will work in conjunction with files too: `lite . main.c`

**Comment by stefanos82** [comment]
> To mimic lite's old behaviour you should pass it `.` as an argument. This will work in conjunction with files too: `lite . main.c`

I honestly don't know what to say...this logic does not make any sense to me :confused:
