### ISSUE TITLE
[question] Implement text user interface (TUI)

### ISSUE THREAD

**Issue by anddam** [rxi/lite#155]
Is adding a TUI something that has been thought about or something you'd like to think about/discuss?

The idea would be to have a behavior akin to Emacs, with its Xorg or terminal rendering basically providing the same interface/features.

**Comment by rxi** [comment]
This is far outside the scope of lite -- realistically to support this you'd have to re-implement the vast majority of lite. You would essentially be writing an entirely new editor.

**Comment by anddam** [comment]
Thanks for clarifying it.
