### ISSUE TITLE
Documentation? I really don't know how to use Lite

### ISSUE THREAD

**Issue by ianpan870102** [rxi/lite#158]
I've just started trying out in the past hour.... and I love the beautiful minimalist UI.
However, I have trouble performing the most basic tasks like deleting/creating a new file, opening a project etc.
Any documentation or pointers would be appreciated!

**Comment by 128p** [comment]
It takes a lot reading but I'm slowly crawling my way to implement Emacs keybindings (and hopefully the C-x <key> thing).

Btw, for closing a doc (an opened file), hit: **Ctrl+W**.

**Comment by ur4ltz** [comment]
This is the output of the keymap variable by the luainspect utility.
This is of course not documentation, but it’s much easier to understand than looking in files ..

{
  add = <function 1>,
  get_binding = <function 2>,
  map = {
    ["alt+1"] = { "root:switch-to-tab-1" },
    ["alt+2"] = { "root:switch-to-tab-2" },
    ["alt+3"] = { "root:switch-to-tab-3" },
    ["alt+4"] = { "root:switch-to-tab-4" },
    ["alt+5"] = { "root:switch-to-tab-5" },
    ["alt+6"] = { "root:switch-to-tab-6" },
    ["alt+7"] = { "root:switch-to-tab-7" },
    ["alt+8"] = { "root:switch-to-tab-8" },
    ["alt+9"] = { "root:switch-to-tab-9" },
    ["alt+i"] = { "root:switch-to-up" },
    ["alt+j"] = { "root:switch-to-left" },
    ["alt+k"] = { "root:switch-to-down" },
    ["alt+l"] = { "root:switch-to-right" },
    ["alt+return"] = { "core:toggle-fullscreen" },
    ["alt+shift+i"] = { "root:split-up" },
    ["alt+shift+j"] = { "root:split-left" },
    ["alt+shift+k"] = { "root:split-down" },
    ["alt+shift+l"] = { "root:split-right" },
    backspace = { "doc:backspace" },
    ["ctrl+'"] = { "quote:quote" },
    ["ctrl+/"] = { "doc:toggle-line-comments" },
    ["ctrl+;"] = { "macro:play" },
    ["ctrl+["] = { "doc:move-to-previous-block-start" },
    ["ctrl+\\"] = { "treeview:toggle" },
    ["ctrl+]"] = { "doc:move-to-next-block-end" },
    ["ctrl+a"] = { "doc:select-all" },
    ["ctrl+backspace"] = { "doc:delete-to-previous-word-start" },
    ["ctrl+c"] = { "doc:copy" },
    ["ctrl+d"] = { "find-replace:select-next", "doc:select-word" },
    ["ctrl+delete"] = { "doc:delete-to-next-word-end" },
    ["ctrl+down"] = { "doc:move-lines-down" },
    ["ctrl+end"] = { "doc:move-to-end-of-doc" },
    ["ctrl+f"] = { "find-replace:find" },
    ["ctrl+g"] = { "doc:go-to-line" },
    ["ctrl+home"] = { "doc:move-to-start-of-doc" },
    ["ctrl+j"] = { "doc:join-lines" },
    ["ctrl+l"] = { "doc:select-lines" },
    ["ctrl+left"] = { "doc:move-to-previous-word-start" },
    ["ctrl+n"] = { "core:new-doc" },
    ["ctrl+o"] = { "core:open-file" },
    ["ctrl+p"] = { "core:find-file" },
    ["ctrl+pagedown"] = { "root:move-tab-right" },
    ["ctrl+pageup"] = { "root:move-tab-left" },
    ["ctrl+q"] = { "core:quit" },
    ["ctrl+r"] = { "find-replace:replace" },
    ["ctrl+return"] = { "doc:newline-below" },
    ["ctrl+right"] = { "doc:move-to-next-word-end" },
    ["ctrl+s"] = { "doc:save" },
    ["ctrl+shift+;"] = { "macro:toggle-record" },
    ["ctrl+shift+["] = { "doc:select-to-previous-block-start" },
    ["ctrl+shift+]"] = { "doc:select-to-next-block-end" },
    ["ctrl+shift+backspace"] = { "doc:delete-to-previous-word-start" },
    ["ctrl+shift+d"] = { "doc:duplicate-lines" },
    ["ctrl+shift+delete"] = { "doc:delete-to-next-word-end" },
    ["ctrl+shift+end"] = { "doc:select-to-end-of-doc" },
    ["ctrl+shift+f"] = { "project-search:find" },
    ["ctrl+shift+home"] = { "doc:select-to-start-of-doc" },
    ["ctrl+shift+k"] = { "doc:delete-lines" },
    ["ctrl+shift+left"] = { "doc:select-to-previous-word-start" },
    ["ctrl+shift+p"] = { "core:find-command" },
    ["ctrl+shift+q"] = { "reflow:reflow" },
    ["ctrl+shift+return"] = { "doc:newline-above" },
    ["ctrl+shift+right"] = { "doc:select-to-next-word-end" },
    ["ctrl+shift+s"] = { "doc:save-as" },
    ["ctrl+shift+tab"] = { "root:switch-to-previous-tab" },
    ["ctrl+tab"] = { "root:switch-to-next-tab" },
    ["ctrl+up"] = { "doc:move-lines-up" },
    ["ctrl+v"] = { "doc:paste" },
    ["ctrl+w"] = { "root:close" },
    ["ctrl+x"] = { "doc:cut" },
    ["ctrl+y"] = { "doc:redo" },
    ["ctrl+z"] = { "doc:undo" },
    delete = { "doc:delete" },
    down = { "project-search:select-next", "autocomplete:next", "command:select-next", "doc:move-to-next-line" },
    end = { "doc:move-to-end-of-line" },
    escape = { "autocomplete:cancel", "command:escape", "doc:select-none" },
    f3 = { "find-replace:repeat-find" },
    f5 = { "project-search:refresh" },
    home = { "doc:move-to-start-of-line" },
    ["keypad enter"] = { "command:submit", "doc:newline" },
    left = { "doc:move-to-previous-char" },
    pagedown = { "doc:move-to-next-page" },
    pageup = { "doc:move-to-previous-page" },
    return = { "project-search:open-selected", "command:submit", "doc:newline" },
    right = { "doc:move-to-next-char" },
    ["shift+backspace"] = { "doc:backspace" },
    ["shift+delete"] = { "doc:delete" },
    ["shift+down"] = { "doc:select-to-next-line" },
    ["shift+end"] = { "doc:select-to-end-of-line" },
    ["shift+f3"] = { "find-replace:previous-find" },
    ["shift+home"] = { "doc:select-to-start-of-line" },
    ["shift+left"] = { "doc:select-to-previous-char" },
    ["shift+pagedown"] = { "doc:select-to-next-page" },
    ["shift+pageup"] = { "doc:select-to-previous-page" },
    ["shift+right"] = { "doc:select-to-next-char" },
    ["shift+tab"] = { "doc:unindent" },
    ["shift+up"] = { "doc:select-to-previous-line" },
    tab = { "autocomplete:complete", "command:complete", "doc:indent" },
    up = { "project-search:select-previous", "autocomplete:previous", "command:select-previous", "doc:move-to-previous-line" }
  },
  modkeys = {},
  on_key_pressed = <function 3>,
  on_key_released = <function 4>,
  reverse_map = {
    ["autocomplete:cancel"] = "escape",
    ["autocomplete:complete"] = "tab",
    ["autocomplete:next"] = "down",
    ["autocomplete:previous"] = "up",
    ["command:complete"] = "tab",
    ["command:escape"] = "escape",
    ["command:select-next"] = "down",
    ["command:select-previous"] = "up",
    ["command:submit"] = "return",
    ["core:find-command"] = "ctrl+shift+p",
    ["core:find-file"] = "ctrl+p",
    ["core:new-doc"] = "ctrl+n",
    ["core:open-file"] = "ctrl+o",
    ["core:quit"] = "ctrl+q",
    ["core:toggle-fullscreen"] = "alt+return",
    ["doc:backspace"] = "backspace",
    ["doc:copy"] = "ctrl+c",
    ["doc:cut"] = "ctrl+x",
    ["doc:delete"] = "delete",
    ["doc:delete-lines"] = "ctrl+shift+k",
    ["doc:delete-to-next-word-end"] = "ctrl+delete",
    ["doc:delete-to-previous-word-start"] = "ctrl+shift+backspace",
    ["doc:duplicate-lines"] = "ctrl+shift+d",
    ["doc:go-to-line"] = "ctrl+g",
    ["doc:indent"] = "tab",
    ["doc:join-lines"] = "ctrl+j",
    ["doc:move-lines-down"] = "ctrl+down",
    ["doc:move-lines-up"] = "ctrl+up",
    ["doc:move-to-end-of-doc"] = "ctrl+end",
    ["doc:move-to-end-of-line"] = "end",
    ["doc:move-to-next-block-end"] = "ctrl+]",
    ["doc:move-to-next-char"] = "right",
    ["doc:move-to-next-line"] = "down",
    ["doc:move-to-next-page"] = "pagedown",
    ["doc:move-to-next-word-end"] = "ctrl+right",
    ["doc:move-to-previous-block-start"] = "ctrl+[",
    ["doc:move-to-previous-char"] = "left",
    ["doc:move-to-previous-line"] = "up",
    ["doc:move-to-previous-page"] = "pageup",
    ["doc:move-to-previous-word-start"] = "ctrl+left",
    ["doc:move-to-start-of-doc"] = "ctrl+home",
    ["doc:move-to-start-of-line"] = "home",
    ["doc:newline"] = "return",
    ["doc:newline-above"] = "ctrl+shift+return",
    ["doc:newline-below"] = "ctrl+return",
    ["doc:paste"] = "ctrl+v",
    ["doc:redo"] = "ctrl+y",
    ["doc:save"] = "ctrl+s",
    ["doc:save-as"] = "ctrl+shift+s",
    ["doc:select-all"] = "ctrl+a",
    ["doc:select-lines"] = "ctrl+l",
    ["doc:select-none"] = "escape",
    ["doc:select-to-end-of-doc"] = "ctrl+shift+end",
    ["doc:select-to-end-of-line"] = "shift+end",
    ["doc:select-to-next-block-end"] = "ctrl+shift+]",
    ["doc:select-to-next-char"] = "shift+right",
    ["doc:select-to-next-line"] = "shift+down",
    ["doc:select-to-next-page"] = "shift+pagedown",
    ["doc:select-to-next-word-end"] = "ctrl+shift+right",
    ["doc:select-to-previous-block-start"] = "ctrl+shift+[",
    ["doc:select-to-previous-char"] = "shift+left",
    ["doc:select-to-previous-line"] = "shift+up",
    ["doc:select-to-previous-page"] = "shift+pageup",
    ["doc:select-to-previous-word-start"] = "ctrl+shift+left",
    ["doc:select-to-start-of-doc"] = "ctrl+shift+home",
    ["doc:select-to-start-of-line"] = "shift+home",
    ["doc:select-word"] = "ctrl+d",
    ["doc:toggle-line-comments"] = "ctrl+/",
    ["doc:undo"] = "ctrl+z",
    ["doc:unindent"] = "shift+tab",
    ["find-replace:find"] = "ctrl+f",
    ["find-replace:previous-find"] = "shift+f3",
    ["find-replace:repeat-find"] = "f3",
    ["find-replace:replace"] = "ctrl+r",
    ["find-replace:select-next"] = "ctrl+d",
    ["macro:play"] = "ctrl+;",
    ["macro:toggle-record"] = "ctrl+shift+;",
    ["project-search:find"] = "ctrl+shift+f",
    ["project-search:open-selected"] = "return",
    ["project-search:refresh"] = "f5",
    ["project-search:select-next"] = "down",
    ["project-search:select-previous"] = "up",
    ["quote:quote"] = "ctrl+'",
    ["reflow:reflow"] = "ctrl+shift+q",
    ["root:close"] = "ctrl+w",
    ["root:move-tab-left"] = "ctrl+pageup",
    ["root:move-tab-right"] = "ctrl+pagedown",
    ["root:split-down"] = "alt+shift+k",
    ["root:split-left"] = "alt+shift+j",
    ["root:split-right"] = "alt+shift+l",
    ["root:split-up"] = "alt+shift+i",
    ["root:switch-to-down"] = "alt+k",
    ["root:switch-to-left"] = "alt+j",
    ["root:switch-to-next-tab"] = "ctrl+tab",
    ["root:switch-to-previous-tab"] = "ctrl+shift+tab",
    ["root:switch-to-right"] = "alt+l",
    ["root:switch-to-tab-1"] = "alt+1",
    ["root:switch-to-tab-2"] = "alt+2",
    ["root:switch-to-tab-3"] = "alt+3",
    ["root:switch-to-tab-4"] = "alt+4",
    ["root:switch-to-tab-5"] = "alt+5",
    ["root:switch-to-tab-6"] = "alt+6",
    ["root:switch-to-tab-7"] = "alt+7",
    ["root:switch-to-tab-8"] = "alt+8",
    ["root:switch-to-tab-9"] = "alt+9",
    ["root:switch-to-up"] = "alt+i",
    ["treeview:toggle"] = "ctrl+\\"
  }
}

**Comment by imolein** [comment]
I documented this some weeks ago for myself and made a markdown document out of it #163. Maybe it will be merged.

**Comment by SwissalpS** [comment]
ctrl+shift+p then type what you think a command would be called. For example 'open'. Choose one from list with up/down arrows and return key.
