### ISSUE TITLE
Mouse double-click and drag to select does not work

### ISSUE THREAD

**Issue by ColonelPhantom** [rxi/lite#159]
Normally, one can select text by clicking and dragging. It is also possible to select a word by double clicking.

The natural extension of this is that you can double click, but hold the second press, and then drag around, to select whole words. This works in most programs, including text editors or web browser. But, it doesn't in lite. When I try to double click and drag, the selection simply stays at what I originally double clicked.

The same holds for selecting lines with triple click and drag.

**Comment by ColonelPhantom** [comment]
I implemented this myself, see PR #161 if you would like to put this in upstream lite.

**Comment by rxi** [comment]
I took a look at your pull request but felt it could be implemented a little more cleanly, there was also a minor problem with the caret/non-caret ends of the selection not being in the correct place in all scenarios. I've pushed a commit which should solve the issue. Thanks!
