### ISSUE TITLE
load user plugins automatically

### ISSUE THREAD

**Issue by lordadamson** [rxi/lite#164]
Hi I would love it if lite would load my plugins located in `user/plugins` automatically without having me go and explicitly require each and everyone of them in the `init.lua`

I added this to my `init.lua` as a workaround. It works. But thought I'd share my suggestion in case you find that it's a good idea.

```lua
local files = system.list_dir(EXEDIR .. "/data/user/plugins")

for _, filename in ipairs(files) do
  local modname = "user.plugins." .. filename:gsub(".lua$", "")
  require(modname)
end
```

**Comment by SwissalpS** [comment]
what is the reason for putting plugins in data/user/plugins rather than data/plugins where they do get loaded automatically?

**Comment by lordadamson** [comment]
idk I though you weren't supposed to modify things directly and instead do your overrides in `/data/user` which should make the updates easier and stuff. Maybe you're right though I should just put my stuff in `data/plugins`

**Comment by SwissalpS** [comment]
I currently look at it in an analogy of most linux distros.
core == distro changes (/lib, /bin)
plugins == company managed (local) but also user modified as long as unique names are used
user == user; currently I have one line in user/init.lua loading user/myInit.lua which loads style, config etc.
I also make use of git branches to switch between sets of installed plugins, this is working for now, knock on wood.
lite is really light, even in documentation and comments :)
