### ISSUE TITLE
build from source, line number did not show up on linux arm.

### ISSUE THREAD

**Issue by bokunodev** [rxi/lite#165]
`5.3.0-rc8-0.8-MANJARO-ARM aarch64`
GCC version : `gcc (GCC) 9.2.0`
i successfully build lite from source. but line number is missing.
and also lite allows me to scroll beyond the content.

![Screenshot](https://user-images.githubusercontent.com/54968427/85778103-6ea62080-b74c-11ea-9038-7401a1aefe4f.png)

**Comment by rxi** [comment]
Did you happen to install every single plugin, including the one that hides line numbers and enables boundless scrolling?

**Comment by bokunodev** [comment]
owh, thanks.
and sorry for wasting your time.
