### ISSUE TITLE
Binary not working on i3/arch linux

### ISSUE THREAD

**Issue by beac0n** [rxi/lite#166]
I'm not able to start the application.
I've cloned and built the project, but when starting the application, I get this error message:

> $ ./lite
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  101
  Current serial number in output stream:  102

I'm running arch linux with i3

**Comment by harikt** [comment]
I am using i3. But I build it myself and didn't find any issues on build. May be you should build it, this may help resolve your problem.

**Comment by beac0n** [comment]
Looks more like an issue with X on arch linux, than with i3.

Which linux distro are you using @harikt ?

**Comment by harikt** [comment]
@beac0n I am using Ubuntu 20.04 .

**Comment by awh6al** [comment]
I'm using archlinux with i3 and it works very well.

**Comment by beac0n** [comment]
ok, so it works on my notebook with i3 and arch linux.
I'll check if it works on my desktop when I get home.

Maybe it's an issue with my graphic card driver for nvidia, but that's unlikely imho.

**Comment by beac0n** [comment]
issue is resolved after reboot
