### ISSUE TITLE
font returns wrong character width

### ISSUE THREAD

**Issue by SwissalpS** [rxi/lite#167]
DocView:get_font():get_width('·') returns a value about six times too large for '·' (centred dot)

Noticed this while working on drawwhitespace plugin.

**Comment by rxi** [comment]
This returns the correct value for me using the default font, additionally if I paste a number of `·` characters in a document or the command view they are spaced correctly (the rendering spacing depends on these functions). Are you using the default font? If not does it occur for other fonts besides the one you're using?

**Comment by SwissalpS** [comment]
I use another scale, maybe that is interfering.
style.font = renderer.font.load(EXEDIR .. "/data/fonts/font.ttf", 18 * SCALE)
style.big_font = renderer.font.load(EXEDIR .. "/data/fonts/font.ttf", 34 * SCALE)
style.icon_font = renderer.font.load(EXEDIR .. "/data/fonts/icons.ttf", 16 * SCALE)
style.code_font = renderer.font.load(EXEDIR .. "/data/fonts/monospace.ttf", 22 * SCALE)

**Comment by rxi** [comment]
Can you provide steps to reproduce the erroneous behaviour on a fresh copy of lite? Thanks

**Comment by SwissalpS** [comment]
OK, this is what I did:
```
git clone https://github.com/rxi/lite.git
cd lite
./build.sh
```
- added the drawwhitespace plugin
```
./lite data/plugins/drawwhitespace.lua
```
the whitespace indicators look good except in line 8
the dot for column 40 shows up only after the closing bracket, column 55.
![whitespaceError](https://user-images.githubusercontent.com/161979/85925280-98b82980-b897-11ea-9168-53f18bebea32.png)

Fedora 32, Wayland

**Comment by rxi** [comment]
This was an issue with the `drawwhitespace` plugin iterating per-byte instead of using the utf8 iterator. I've pushed a fix for that plugin which should resolve this

**Comment by SwissalpS** [comment]
cool, thanks :D
