### ISSUE TITLE
Opens in /usr/bin

### ISSUE THREAD

**Issue by Z3r0ish** [rxi/lite#177]
I installed this via yay (yay -S lite) and when ever i launch it it opens on the /usr/bin directory instead of where i open it

**Comment by TorchedSammy** [comment]
you might have to run `lite .`

**Comment by Z3r0ish** [comment]
yeah that fixed it thanks (sorry for the late reply)

**Comment by link2xt** [comment]
Related issue with the reason to open in EXEDIR by default: #153
