### ISSUE TITLE
Why not SDL_ttf ?

### ISSUE THREAD

**Issue by AKonia** [rxi/lite#18]
Maybe it could be better to use SDL_ttf. I know that it doesn't change anything totally, but it could make code more consistent and better for packaging i guess.

**Comment by rxi** [comment]
How do you feel it would make the code more consistent, and how would adding an additional dependency make it better for packaging?

`SDL_ttf` would increase both the code size, overall binary size, and overall complexity of the project. The only advantage it could provide is that it uses freetype which may provide more favourable text rendering, in which case using freetype directly would provide this same advantage without many of the disadvantages.
