### ISSUE TITLE
Mouse scroll whole lines

### ISSUE THREAD

**Issue by Gavin-Holt** [rxi/lite#180]
Hi,

I have been trying to get LITE to scroll down in whole lines with the mouse wheel, the relevant line of code is in core/config.lua:

   config.mouse_wheel_scroll = 50 * SCALE

Q1. Is it safe to change core/init.lua to call core/style.lua before config.lua?
Q2. Would a style.font_height variable make sense?
Q2. In the end can I replace the arbitrary 50 * SCALE with an expression for a single line, including any padding and line height adjustments?

e.g. config.mouse_wheel_scroll = (style.font_height + style.padding + style.padding) * config.line_height * SCALE

Kind Regards Gavin Holt

**Comment by rxi** [comment]
You should be changing the config options in your user module instead of changing them in `config.lua` directly. You can use the `DocView:get_line_height()` function to get the exact height of a line and set `config.mouse_wheel_scroll` to this, or a multiple of this.

**Comment by Gavin-Holt** [comment]
Hi,

I tried your suggestions in my unit.lua:

local DocView = require "core.docview"
config.mouse_wheel_scroll = DocView:get_line_height()

I get an error cited at docview.lua:104.

I suspect get_line_height fails in user init.lua because there are no
buffers open?

KR Gavin

**Comment by rxi** [comment]
The `get_line_height()` function is a method of the DocView and has to be called on an existing instance. You can copy the logic from inside that function and use it with the `style.code_font` if you want to determine the line height without depending on a DocView existing.
