### ISSUE TITLE
Title bar is white, not respecting the choosen theme

### ISSUE THREAD

**Issue by sssaikia** [rxi/lite#182]
I'm on Windows 10, x64. Dark mode is enabled system wide, and `dracula` is set as the theme for lite in `init.lua`, but the title bar always stays white/light, I'm failing to figure out a way to make it dark. No matter what theme I choose, it doesn't change. Is it an expected behavior in windows? If not, what could I be doing wrong?

![Capture](https://user-images.githubusercontent.com/28355489/88328547-3e02d800-cd46-11ea-9a50-7e404aeacc4a.PNG)

I've, for some reason, tried few of the older builds too, same result.

**Comment by martincohen** [comment]
Windows does this by default to every standard application. Only way around it is to customize the frame, which is not trivial and all the methods I've tried have some drawbacks or weird edge cases. And I think it's correct for Lite to leave this problem to be solved by Windows, since it seems like a trivial change on their side.

**Comment by sssaikia** [comment]
> 
> 
> Windows does this by default to every standard application. Only way around it is to customize the frame, which is not trivial and all the methods I've tried have some drawbacks or weird edge cases. And I think it's correct for Lite to leave this problem to be solved by Windows, since it seems like a trivial change on their side.

I'm sorry, it's not yet quite clear to me, do you mean it's an expected behavior? can't we make lite use the system theme? (I have no idea how difficult it is) And when you said 

> customize the frame

 are you talking about changes in the source? before building  the project, or after? like tweaking the registry or something?

**Comment by martincohen** [comment]
What is weird is that you seem to see the white bar even if the Lite is active. is that correct? If yes, can you provide full version of your Windows? Mine is:

![image](https://user-images.githubusercontent.com/421916/88453585-a518ad80-ce68-11ea-83bd-3a97f6cbcfc7.png)

Here's some instructions how you can find it: https://support.techsmith.com/hc/en-us/articles/115001763452-How-to-Check-Windows-10-Build

**Comment by sssaikia** [comment]
Yes, regardless of it's state, whether it's active or inactive, it remains white. 

![Capture](https://user-images.githubusercontent.com/28355489/88454193-719b4a80-ce8b-11ea-8940-48ae94b6a271.PNG)

Well it seems TB of this (about windows) window remains light too. idk what's happening, we have exactly the same version, yet you have it in dark and I in light. Now I understand your previous comment 

> it seems like a trivial change on their side 

I think I'd've to look into some hacks, like registry tweaks or something. Have you applied any additional customization? ( I think not, just wanted to confirm)
Thanks.
