### ISSUE TITLE
Blurry text on macOS

### ISSUE THREAD

**Issue by lordadamson** [rxi/lite#187]
<img width="377" alt="Screen Shot 2020-08-05 at 7 09 17 PM" src="https://user-images.githubusercontent.com/43860544/89443359-76e07b00-d750-11ea-868b-25716ea6837e.png">

<img width="448" alt="Screen Shot 2020-08-05 at 7 21 52 PM" src="https://user-images.githubusercontent.com/43860544/89443936-477e3e00-d751-11ea-9f2a-6c670bcae8e4.png">

It was run on a MacBook Pro (Retina, 13-inch, Mid 2014) with a 13.3-inch (2560 x 1600) display.

Not sure if the image above show the blur, so I provided a screenshot of the same text, same size using a different app to show the difference.

It is not comfortable looking at blurry text for a long time.

**Comment by rxi** [comment]
See #46. I'd recommend reading through all of the issues regarding macos before continuing, as to familiarise yourself with what doesn't work, what things won't be changed (and the reasons why), and forks you might want to try out.
