### ISSUE TITLE
use cmd+s to save on macOS please? :)

### ISSUE THREAD

**Issue by lordadamson** [rxi/lite#188]
on macOS things are usually done with the cmd button. I kept pressed cmd+s and just assumed it saved my work only to discover that it did nothing because when I tried closing the app it said that I have unsaved changes.

Got confused for a while and kept pressing cmd+s several times and noticed that the `*` is not going away. Then I finally tried ctrl+s and that worked.

**Comment by rxi** [comment]
Try installing the `macmodkeys` plugin from the lite-plugins repo

**Comment by lordadamson** [comment]
ok sounds good. Should we close this then or will you consider adding that to lite itself?

**Comment by rxi** [comment]
I'll close this as I don't plan to add this to the core, I've explained my reasons for lack of macos support in some of the other macos related issues.
