### ISSUE TITLE
[Feature request] Open other projects not just base directory

### ISSUE THREAD

**Issue by StarrKiss** [rxi/lite#189]
I cannot figure out how to load Lite to other projects besides its source directory, when I try to open external files, it gives me an error about a locked node. How do I get Lite to work properly?

**Comment by AqilCont** [comment]
Same, I thought that if I put it in path and then run it in the directory I want, it would open that directory, but it still has yet to succeed. I am actually tired of staring at the source code. I've even tried `lite 'pathtodir'` which frustratingly does the exact same thing. It's such a great editor in looks and how light it is, but it's all meaningless if we can't even use it properly :<

**Comment by AqilCont** [comment]
and like many other issues, this just stays open and no one even cares about this massive usability bug.

**Comment by AqilCont** [comment]
Did you try navigating to the directory through command line and typing `lite .`? There are two modules that can also help you called "workspace" and "lastproject" can also help you get back to your previously used dirs :D

**Comment by rxi** [comment]
Pass the project directory name as the first argument to lite or drag a directory onto lite to set the project directory.
