### ISSUE TITLE
Additional syntaxes

### ISSUE THREAD

**Issue by cup** [rxi/lite#19]
Looks like currently only Lua, C and Markdown are supported:

https://github.com/rxi/lite/blob/2eab24032b3419f0eb6fda16265b552b6e599bbb/data/core/syntax.lua#L36
https://github.com/rxi/lite/blob/2eab24032b3419f0eb6fda16265b552b6e599bbb/data/core/syntax.lua#L81
https://github.com/rxi/lite/blob/2eab24032b3419f0eb6fda16265b552b6e599bbb/data/core/syntax.lua#L136

**Comment by rxi** [comment]
Any additional syntaxes to the ones you listed come in the form of plugins, some come with the base program in the [`plugins`](https://github.com/rxi/lite/tree/master/data/plugins) directory. The rest are hosted [here](https://github.com/rxi/lite-plugins), where anyone is welcome to submit a pull request for additional language plugins.
