### ISSUE TITLE
Fira code support

### ISSUE THREAD

**Issue by thantez** [rxi/lite#190]
Hi. Can `lite` support `Fira code` linguistics? If it can please tell me how, otherwise please prepare this compatibility.

**Comment by AqilCont** [comment]
I really want this too, and for other fonts. Just noticing it has been a month and there was no comment whatsoever from the devs...

**Comment by rxi** [comment]
Support for ligatures is not planned. This may be something the [lite-xl](https://github.com/franko/lite-xl) fork is open to adding.
