### ISSUE TITLE
Trying to add my own language syntax. Patterns get recognized, but symbols wont work at all.

### ISSUE THREAD

**Issue by jasaldivara** [rxi/lite#193]
I'm trying to create a new language syntax for assembly. I copied other language_*.lua files from the plugins folder and named the new one as "language_asm.lua" in the same folder.

Patterns work ok when opening files with the .asm extension in Lite, but keywords from the "symbols" table wont work at all.

Language file on plugins folder:
[language_asm.lua](https://github.com/rxi/lite/files/5165231/language_asm.lua.txt)

Screenshot from Lite editor:
[
![Captura de pantalla de 2020-09-02 18-15-00](https://user-images.githubusercontent.com/6020429/92046529-5c49f380-ed48-11ea-8343-86062fc81e9b.png)
](url)

**Comment by imolein** [comment]
You need to add a table with type `symbol` to your patterns table, e.g.
```lua
{ pattern = "[%a]*", type = "symbol" },
```

**Comment by jasaldivara** [comment]
> You need to add a table with type `symbol` to your patterns table, e.g.
> 
> ```lua
> { pattern = "[%a]*", type = "symbol" },
> ```

Thank you!

I added it as:

```lua
 { pattern = "[%a_][%w_]*", type = "symbol"   },
 ```

And now it works ok.
