### ISSUE TITLE
Syntax checks

### ISSUE THREAD

**Issue by Not-Nik** [rxi/lite#20]
It would be great if plugins could underline certain bits of code with a reason that's showed when the user hovers over them. This way we could implement syntax and code-style checks.

**Comment by rxi** [comment]
I agree with this, this is one of the things I want to rework in the `DocView` to allow plugins to do this cleanly. This would either be a case of reorganising the `DocView`'s draw functions so that a plugin can patch in its own underline-drawing, or, extending the `DocView` itself to add auxiliary highlight/underline functionality. The former approach feels more in line with the project.

**Comment by rxi** [comment]
I just pushed a commit which breaks the `DocView`'s draw functions up a little. A plugin can now draw underlines (or anything else) by overriding the `DocView.draw_line_text()` function -- this function is called *after* drawing the line highlight/selection, and *before* drawing the caret. You can chose to call the original `draw_line_text()` function before or after your underline in the override depending on whether you want the line to be drawn above or below the text.

**Comment by Not-Nik** [comment]
Alright, I'll look into scraping errors and warnings for c/c++ tomorrow. Maybe I can also come up with some nice utility for underlining text and showing errors/warnings.

**Comment by Not-Nik** [comment]
Alright, quick update. I made a simple function that draws underline if you give it a line's x and y and a start and end pos (char count). In the screenshot below the function is simply used on every line for a static part of the line. The function checks if the line has enough chars to underline and doesn't draw respectively.
<img width="807" alt="Screen Shot 2020-04-19 at 13 48 58" src="https://user-images.githubusercontent.com/32980656/79679010-31517e00-8245-11ea-9123-208b2630720f.png">

I tried doing this before updating my data folder, and it turns out this was possible before and after your commit, without any changes in code, so I concerned that I'm doing the function hook wrong. At the moment I just get a reference to the existing `draw_line_text` function and then override it, so I can access it later. I'm not programming in Lua often, so this might make no sense.

**Comment by rxi** [comment]
Overriding the old `draw_line_text` function would have *kind-of* worked, but as the function previously drew the selections, text and carets, the ordering would be weird. Eg. you typically always want the selection drawn below and the caret drawn above -- the update fixes this as the function draws *only* the text.

Not sure if anything else was unclear; the [indentguide plugin](https://github.com/rxi/lite-plugins/blob/master/indentguide.lua) overrides the `draw_line_text` function as I described to draw indent guides, so might work as a good reference of how this kind of thing should be done:

![image](https://user-images.githubusercontent.com/3920290/79682032-e1f45900-8216-11ea-9a3b-78f20d190d18.png)

**Comment by Not-Nik** [comment]
Good to know. I'm using the same override, just wasn't sure because I haven't done something like that in Lua before. Next step will be to actually check for errors in warnings.

**Comment by rxi** [comment]
Along with the API changes a [linter plugin](https://github.com/drmargarido/linters) has since been developed which I believe provides the functionality you described in the initial post. Closing the issue as I'm considering it resolved now.
