### ISSUE TITLE
`CTRL+W` should close lite if the current view is empty

### ISSUE THREAD

**Issue by mathewmariani** [rxi/lite#203]
I noticed that the default behavior for `CTRL+W` (to close windows) doesn't close lite itself.

As expected `CTRL+W` closes the current document but if the current document is empty I feel the expected behavior should be to close lite itself.

**Comment by harikt** [comment]
I dislike `ctrl+w` closing the open application.

**Comment by Tmpod** [comment]
I agree with harikt, `Ctrl+Q` is a nicer way to quit lite imo. Either way, if you really want that feature just write a plugin, don't forget that's one of lite's philosophies ;)

It would be a matter of creating a file in your plugins directory with something along the lines of 
```lua
local core = require "core"
local command = require "core.command"
local keymap = require "core.keymap"
|
local function close_tab_or_quit_command()
    if core.active_view.doc == nil then
        command.perform("core:quit")
    else
        command.perform("root:close")
    end
end

-- We need to add a command so that we can then add the keybind
command.add(nil, { ["core:close-tab-or-quit"] = close_tab_or_quit_command })

keymap.add { ["ctrl+w"] = "core:close-tab-or-quit" }
``` 

Hope this helps :)

**Comment by mathewmariani** [comment]
It helps, thank you. I just don't like the idea of a default system behavior being implemented through a plugin

**Comment by Tmpod** [comment]
lite is guided by some strong and opinionated philosophies, so these kinds of clashes are bound to happen, and that's where the plugin system comes in really handy :wink:
