### ISSUE TITLE
Convergent Evolution?

### ISSUE THREAD

**Issue by Gavin-Holt** [rxi/lite#21]
Hi

I really like the Lite editor - really quick and really clean. Reminds me of [TextAdept](https://foicica.com/textadept/) - an example of [convergent evolution](https://en.wikipedia.org/wiki/Convergent_evolution)?

Should you choose to add functionality I think Textadept may offer a map to follow. The keyboard driven extension [TextRedux](http://rgieseke.github.io/textredux/) is also worth a look.

I have been trying to mold the two together to produce a curses WIN32 editor looking much like Lite.

Some questions about the current version:

Q1. Is there a way to list all the available commands?

Q2. Can key bindings be associated with a specific mode? 
I like ESC to core:quit - will this mess up the autocomplete script?

Q3. Is there a way to execute arbitrary Lua code - see my [post](https://foicica.com/lists/code/202002/5380.html) on command line editing (sorry about the lack of CRLF in the post - still not sure how to set up gmail for this mailing list)

Q4. Documentation??

Kind Regards Gavin Holt

**Comment by rxi** [comment]
1. No, though this can be done easily by adding some lua code to iterate the `command.map` table in `core.command` and print the keys
2. Yes, key bindings map to commands which it iterates in sequence until one of the commands' predicate functions returns `true` -- see the default binding for `tab` in `core.keymap`
3. Bit of a long post, but to answer your initial question: Yes. You could add a command that uses the `loads()` to compile a lua string into a function
4. No

**Comment by Gavin-Holt** [comment]
Many thanks, replies as streamlined as the application.

Kind Regards Gavin Holt
