### ISSUE TITLE
tab key does not set

### ISSUE THREAD

**Issue by Teghit** [rxi/lite#222]
Your program is awesome, thank you for it. I got your code and build in my Raspberry Pi for test it.
When I created a Makefile for do anything in C, I saw [this](https://ibb.co/286nW9L), lite defined tab as two spaces, then, I came here to view any your answer. 
That is an error?!

Excuse me for my English, I'm a Brazilian and beginner in that language.

**Comment by mateusmds** [comment]
> Your program is awesome, thank you for it. I got your code and build in my Raspberry Pi for test it.
> When I created a Makefile for do anything in C, I saw [this](https://ibb.co/286nW9L), lite defined tab as two spaces, then, I came here to view any your answer. 
> That is an error?!
> 
> Excuse me for my English, I'm a Brazilian and beginner in that language.
> 

You can edit the size of tab in user config (``data/user/init``) changing the config.indent_size and config.tab_size (I don't know exactly what this last one does, I just edited the first and worked for me).
But no, it's not a bug.

**Comment by Teghit** [comment]
Thank you for your answers but this is not the problem... When I save some code, **lite** define tab as spaces (`0x20`) instead Horizontal Tabulation (`0x09` or `\t`).
Try to write a Makefile and run it.

**Comment by mateusmds** [comment]
> Thank you for your answers but this is not the problem... When I save some code, **lite** define tab as spaces (`0x20`) instead Horizontal Tabulation (`0x09` or `\t`).
> Try to write a Makefile and run it.

I don't know the problem with this but ok. You can make a plug-in to replace (gsub) every "\s" * tab_size in your code that isn't inside a string

**Comment by sleepycrow** [comment]
Putting `config.tab_type = "hard"` in your `data/user/init.lua` file should switch you to hard tabs.

**Comment by Teghit** [comment]
Thanks, it's this. I didn't found other value for this field, resolved!
