### ISSUE TITLE
Tree view is not resizable.

### ISSUE THREAD

**Issue by rgrams** [rxi/lite#23]
The mouse cursor changes when you hover over the edge of the Tree-view area, but nothing happens when you drag it. Dragging to resize split editor panels works just fine.

**Comment by rxi** [comment]
This is intended behaviour, the `TreeView` size is set through a field in the config module.

**Comment by rgrams** [comment]
Ohh, OK. In that case, the only real issue is that the mouse cursor still changes to the left/right resize cursor at the edge of it.
