### ISSUE TITLE
Add teal-lang and nelua syntax highlighting

### ISSUE THREAD

**Issue by mundusnine** [rxi/lite#234]
So I intend to add teal(typed lua) and nelua syntax highlighting, should this be added to the plugins repo or to the main repo ?

Also, it would be maybe interesting to add .d.tl definitions for easily making plugins with teal for lite since teal directly transpiles to lua. This is just a thought maybe this wouldn't be desired on your end which I would understand.

- [X] Teal
- [ ] Nelua
Happy new year :)

**Comment by quadroli** [comment]
Happy new year to you to 🥳

**Comment by Tmpod** [comment]
Yeah this issue should have been opener over on the plugins repo. Anyways, thanks for the contribution, and happy new year!

**Comment by Andre-LA** [comment]
Just for the sake of sharing, but there is a nelua syntax highlighting here:
https://github.com/AbdulKalam21/nelua-lite-xl/
