### ISSUE TITLE
Changing theme dynamically

### ISSUE THREAD

**Issue by benstigsen** [rxi/lite#237]
Is there any way to change the color theme dynamically? I've made a plugin, that depending on the time changes to a certain theme. But it does this by `require "user.colors.xxx"` and then a `core.redraw = true` which works fine for a while, but when having this editor open for a long time, I'm wondering if it's bad practice to require the same files over and over again.

**Comment by Tmpod** [comment]
I don't immediately see any problem with that approach; that would be what I would do too.

**Comment by benstigsen** [comment]
I make it do this every minute to test it out. But for proper usage it's probably only going to be used twice in 24 hours, so unless someone has lite open for like several weeks, it shouldn't be a problem.

**Comment by benstigsen** [comment]
After further consideration, it would probably be better to just load the themes once, then execute the code, instead of requiring it each time. This would be more performant and wouldn't have to load a file each time.

**Comment by benstigsen** [comment]
I've now made it load themes on initialization loading things into memory once. So far I've had no trouble with using it.

**Comment by Tmpod** [comment]
Nice to hear!

**Comment by benstigsen** [comment]
https://github.com/rxi/lite-plugins/pull/118
