### ISSUE TITLE
Is there way to change background text on start window?

### ISSUE THREAD

**Issue by uvicorn** [rxi/lite#238]
![изображение](https://user-images.githubusercontent.com/59787538/104499052-17e03580-560f-11eb-8804-58c8863f0e5a.png)
I want to view current time on this spot

**Comment by Tmpod** [comment]
That text drawing is done by a local function `draw_text` in `core/rootview.lua` which is used in `EmptyView:draw`. You could extend the latter and insert a `renderer.draw_text` call with something like `os.date("%a %x %X", os.time())` in it. Alternatively you could just edit the actual core file.
