### ISSUE TITLE
how to go to the next occurrence of the desired pattern?

### ISSUE THREAD

**Issue by uvicorn** [rxi/lite#239]
![изображение](https://user-images.githubusercontent.com/59787538/104512081-3c90d900-5620-11eb-9e2d-7054d3466611.png)

**Comment by D10f** [comment]
Once you find a match, press Ctrl+D to jump to the next occurrence if there's any. This works also without having to use `Find Text` specifically by just highlighting some piece of code.

Note that in other code editors the same shortcut Ctrl+D will not only jump but also select (it creates a new cursor) the next occurrence. I still haven't found a way to do that in Lite, though I hope it's enabled soon.

**Comment by drmargarido** [comment]
To do that with find text I just press Ctrl+F and enter multiple times. Since the cursor stays at the end of the found word, if you do the find again with the same text it will jump to the next occurrence.

**Comment by uvicorn** [comment]
Thx!
