### ISSUE TITLE
Add a maximize command.

### ISSUE THREAD

**Issue by rgrams** [rxi/lite#24]
99% of the time I would like the program to start up with the window maximized. Yes, I can use operating system shortcuts to maximize it, but that's one extra thing I have to do every single time. 

Fullscreen is nice (and it's easy to call in your user\init so it starts with it), but for everyday use I like to see my taskbar, so maximizing is better.

**Comment by rxi** [comment]
Added the `system.set_window_mode()` function.
`system.set_window_mode("maximized")` can now be called from `user/init.lua` to start `lite` maximized.
