### ISSUE TITLE
Text Antialiasing

### ISSUE THREAD

**Issue by krthknch** [rxi/lite#254]
![vscode-lite](https://user-images.githubusercontent.com/60850111/107987832-a48f6200-6fc6-11eb-95b8-6d8085d849b3.png)

The lite editor in comparison is visibly darker at approximately the same scale

**Comment by aqilc** [comment]
Just go into the core module and change the weight of the font, and use [franko/lite-xl](https://github.com/franko/lite-xl) for better font rendering. I don't think @rxi will make many modifications to the editor anyways, especially in the area of text rendering.

**Comment by krthknch** [comment]
Thank you for replying. I switched out the font for a thicker one and it looked fine. Might I suggest making the default font a higher weight. The fork you suggested seems to work fine too.

**Comment by aqilc** [comment]
No problem! Feel free to close this issue if you feel satisfied.
