### ISSUE TITLE
build.sh script not working for me on Debian Buster. Am I missing a step?

### ISSUE THREAD

**Issue by ghost** [rxi/lite#264]
src/renderer.h:4:10: fatal error: SDL2/SDL.h: No such file or directory
 #include <SDL2/SDL.h>

I have not built an app from source before. I chmod +x  build.sh and then ./build.sh to execute it, but the compiler gives me this message. Am I missing something?

**Comment by quou** [comment]
You need to have SDL installed. Try running `sudo apt install libsdl2-dev` before compiling.

**Comment by ghost** [comment]
Yea, I was scrolling in the previous issues and saw this just a minute ago. I am missing the dev package for libSDL2. Thanks!
