### ISSUE TITLE
New Key Binding: Ctrl + Shift + Z to redo

### ISSUE THREAD

**Issue by sanket143** [rxi/lite#279]
Currently, we can redo with `Ctrl + Y`. It'll be great to have `Ctrl + Shift + Z` to redo since it's much more intuitive and vscode also uses it so it'll be helpful for those who are coming from vscode.

**Comment by quou** [comment]
Put this in your `init.lua`

```lua
keymap.add {
​  [​"​ctrl+shift+z"​] ​=​ { ​"​doc:redo"​ },
}
```
Reload the user module and now you have `ctrl+shift+z` support.

**Comment by sanket143** [comment]
got it thanks
