### ISSUE TITLE
Extremely small on HiDPI screens

### ISSUE THREAD

**Issue by Daaniiieel** [rxi/lite#28]
The title explains it. My real dpi is 144, it seems to use 96 dpi.
![DeepinScreenshot_20200417091423](https://user-images.githubusercontent.com/41679054/79542410-e04a5a00-808b-11ea-9a0c-b504910b57f7.png)
Can be fixed by modifying main.c (return 1.0 -> return 1.4)

**Comment by rxi** [comment]
I'm assuming you're on macOS based on where your caret is in the screenshot -- this ended up being more hassle than its worth for me to get working with macOS. As I don't have a mac myself it isn't "officially" a supported platform by `lite`, though it will compile and, *for the most part* run fine on it.

If this is easily fixable in code (in the same kind of way the scale is resolved in windows) then I'd likely accept it as a pull request, but to my knowledge this isn't possible and isn't something I'm going to pursue myself. 

To practically circumvent this problem, `lite` supports the `LITE_SCALE` environment variable which when set to a given scaling factor will override the value it tries to determine from your DPI.

**Comment by Daaniiieel** [comment]
No :), I am on manjaro. Thank you for the lite_scale tip, now I don't need to recompile it (even that it's really fast and beautiful). Thanks again as I said

**Comment by Daaniiieel** [comment]
EDIT: it doesn't seem to work with LITE_SCALE: I tried 
`set LITE_SCALE = 1.35`

`lite`

and it didn't work

**Comment by p410n3** [comment]
Try export instead of set

**Comment by Daaniiieel** [comment]
True, my bad
by the way g'day palone

**Comment by p410n3** [comment]
I found a way to scale without having to set an environment variable. Basically reloading a bunch of stuff from the config and style sections

This might feel like unnecesarily bloating the user config, but

1) Changing the core files is a big no no if you wanna update
2) The user module will be loaded after everything else when the application starts, so just setting _SCALE wouldnt do anything

Makes the config more portable and should work between multiple users.

```lua
-- My user Settings

local keymap = require "core.keymap"
local config = require "core.config"
local style = require "core.style"

-- Needed to acces certain functions
local common = require "core.common"

-- Set the scale variable to make the whole editor scale
local _SCALE = 1.2

-- Copied from: core/config.lua
config.treeview_size = 200 * _SCALE

-- Copied from: core/style.lua
style.padding = { x = common.round(14 * _SCALE), y = common.round(7 * _SCALE) }
style.divider_size = common.round(1 * _SCALE)
style.scrollbar_size = common.round(4 * _SCALE)
style.caret_width = common.round(2 * _SCALE)
style.tab_width = common.round(170 * _SCALE)

style.font = renderer.font.load(_EXEDIR .. "/data/fonts/font.ttf", 14 * _SCALE)
style.big_font = renderer.font.load(_EXEDIR .. "/data/fonts/font.ttf", 34 * _SCALE)
style.icon_font = renderer.font.load(_EXEDIR .. "/data/fonts/icons.ttf", 14 * _SCALE)
style.code_font = renderer.font.load(_EXEDIR .. "/data/fonts/monospace.ttf", 13.5 * _SCALE)

-- key binding:
-- keymap.add { ["ctrl+escape"] = "core:quit" }
```

**Comment by lordadamson** [comment]
Hi, I solved was solved for me by setting `_SCALE` to `1.5` in the beginning of `data/core/style.lua`

Like this:

```lua
local common = require "core.common"
local style = {}

_SCALE = 1.5

... the rest of the file goes here
```

**Comment by p410n3** [comment]
Just keep in mind that changing stuff in core might break on updates

**Comment by lordadamson** [comment]
that is true. I did that before seeing your solution. I really dislike having to put all this just to change the scale though :/ I wish a better way exists.

**Comment by lordadamson** [comment]
Also imagine in a future update _SCALE is used in other variables that you did not include in here. Or maybe a different function is called to set the padding or whatever. You'd have to rediscover what things to copy all over again.

**Comment by rxi** [comment]
> that is true. I did that before seeing your solution. I really dislike having to put all this just to change the scale though :/ I wish a better way exists.

This is the purpose of the environment variable. Setting one is trivial to do on Windows and Linux thus I'm a little confused about the effort being put in to avoid doing so

**Comment by Daaniiieel** [comment]
I think I am gonna close this issue since three separate solutions were published.
Thank you all for commenting, feel free to unclose  if you want to do so :)

**Comment by lordadamson** [comment]
Here's what I ended up doing:

* rename lite to lite.bin
* Create a script called lite with the following content:
```sh
#!/usr/bin/env sh

export LITE_SCALE=1.5
nohup lite.bin $@ > /dev/null &
```

* give it execute permissions

Now I can say `lite .` in any directory and it would work just fine. (Assuming the lite directory is in your PATH)

**Comment by Jipok** [comment]
There is a nicer solution through a plugin. Just add this to your config:
```lua
local scale = require "plugins.scale"
config.scale_mode = "ui"
scale.set_scale(1.25)
```
