### ISSUE TITLE
Run "lite ." cleanly from the terminal

### ISSUE THREAD

**Issue by supertsumu** [rxi/lite#304]
Hi! Started using lite and I love it so far. But I often find myself opening the current directory in light from the terminal using "lite .". This will cause the terminal to host the application and will not be usable until the program terminates. Is there a way to use "lite ." while still being able to use that terminal window? Thanks!

**Comment by rncar** [comment]
in linux you can use: `lite . &`

**Comment by supertsumu** [comment]
Thanks! I set a alias in my zshrc to execute this and it works perfectly.
