### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [rxi/lite#308]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

*So... I would like to know the difference between lite-xl/lite-xl and rxi/lite.*

**Comment by pegvin** [comment]
the project isn't active, lite-xl/lite-xl is a text editor built on top of lite by a different lite loving community, lite-xl/lite-xl fixes many bugs & has introduced new features, you should look there.

**Comment by ghost** [comment]
Hi pegvin.

> the project isn't active, lite-xl/lite-xl is a text editor built on top of lite by a different lite loving community, lite-xl/lite-xl fixes many bugs & has introduced new features, you should look there.

thank you for feedback.
