### ISSUE TITLE
attempt to concatenate global '_EXEDIR' (a nil value)

### ISSUE THREAD

**Issue by mrtnpwn** [rxi/lite#35]
I downloaded the `lite.zip` from the releases page, unzipped it into a `.lite` directory into my user folder and ran the executable from this folder just to check out if it opened without crashing or something.

![Screenshot 1](https://i.imgur.com/Im1EK7C.png)

Then, I decided to add this folder to my PATH, it runs but instantly crashes with the message: `attempt to concatenate global '_EXEDIR' (a nil value)`:

![Screenshot 2](https://i.imgur.com/dBtc6vS.png)

**Comment by rxi** [comment]
It looks like you might have downloaded an older version -- that error shouldn't be possible in the current version. Would you be able to grab the `1.01` version and try again?

**Comment by mrtnpwn** [comment]
> It looks like you might have downloaded an older version

Nope, I got the latest release. I even tried to build from source and use that, but it's the same issue.

**Comment by rxi** [comment]
Quite confused in that case! My assumption that it was the old version was based on the fact that the [6th line in the current version](https://github.com/rxi/lite/blob/master/src/main.c#L110) is directly following a line which *already concatenates `_EXEDIR`*, it makes no sense that the first succeeds and the second doesn't. `_EXEDIR` being `nil` also doesn't make sense as it's set through the C API directly.

In the [old version, the 6th line](https://github.com/rxi/lite/blob/f96b08dfc8a7c239438e726925444d07434bf561/src/main.c#L67) is the first use of `_EXEDIR` which is based on the `match` function succeeding, which would result in `nil` if it failed.

**Comment by mrtnpwn** [comment]
For now I made a workaround for this using a global zsh alias that just executes it with the whole path

**Comment by Gavin-Holt** [comment]
Hi 

I think all the uppercase global variables have been modified, no more underscores.

Kind Regards Gavin Holt

**Comment by rxi** [comment]
Closing this as `_EXEDIR` has been renamed in the current version, and this doesn't seem to be a problem that anyone else has had. If there's a problem with `EXEDIR` in the current version a new issue can be made.
