### ISSUE TITLE
Customize scrollbar width

### ISSUE THREAD

**Issue by flamendless** [rxi/lite#36]
The scrollbar is too narrow. It requires too much precision when trying to scroll a split because the cursor sometimes becomes the adjustment pointer.

Example: in a left-right window split. Trying to scroll in the left window.

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rxi** [comment]
This can be customised by setting `style.scrollbar_size` to a greater value in your `data/user/init.lua` file
