### ISSUE TITLE
Ability to allow case insensitive keywords to language descriptions

### ISSUE THREAD

**Issue by Nullious** [rxi/lite#4]
see language_6502.lua I'd like to allow upper and lowercase keywords for this.

**Comment by rxi** [comment]
I'm not convinced of the *general* usefulness of adding this as a feature. If you do want to support both lowercase and uppercase versions of keywords in a syntax, the best approach would probably be to build the `symbols` table programmatically: storing the keywords in a `keywords` table which you iterate and build the `symbols` table from.

**Comment by Nullious** [comment]
Yeah that was my second option. I'm not 100% sure of other languages that would allow case insensitive keywords other than asm.

**Comment by zeevro** [comment]
[This Wikipedia article](https://en.wikipedia.org/wiki/Case_sensitivity#In_programming_languages) lists some popular languages that are case-insensitive, and also mentions some special uses for casing in some languages.
