### ISSUE TITLE
Toggle Statusview

### ISSUE THREAD

**Issue by Gavin-Holt** [rxi/lite#40]
Hi,

Would you consider implementing a Toggle Statusview command?

I'm working from home on a small laptop with old eyes, using the fantastic full screen mode I get 26 and one half lines, that means the status bar is taking about 4% of the available screen.

Also I would commend the aesthetics of full screen without status bar - it feels very pure :)

Kind Regards Gavin Holt

**Comment by rxi** [comment]
I ended up fixing the bug you were experiencing before when you presumably forced the height of the `StatusView` to zero -- you'll need to grab the master version of the project from the repo; the change was purely lua so doesn't require a re-compile. I've added the `hidestatus` plugin to [plugins repo](https://github.com/rxi/lite-plugins).

**Comment by Gavin-Holt** [comment]
Very kind, thank you. 

I have made language_kix.lua and placed it in my very first repository: 
https://github.com/Gavin-Holt/LitePlugin 
- sorry I have yet to learn how to do a pull request. 

Kind Regards Gavin Holt
