### ISSUE TITLE
Q: Would toolbar be considered as core element or addon?

### ISSUE THREAD

**Issue by okass** [rxi/lite#41]
Just as title says. I mean the toolbar at the top of window like usually.

**Comment by rxi** [comment]
If this was added, and you a native toolbar was wanted, it would have to be done on the C side, I imagine, though, the fact that the program uses SDL would make this difficult. A non-native toolbar could be implemented but would conflict with a lot of the current UI choices (eg. no support for interactive overlapping ui elements) thus would require modifying the core to support it.

In either case, along with context menus, this is not something I plan to add to the project.
