### ISSUE TITLE
A user's feedback if I may

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite#50]
Hey @rxi,

I hope you are doing great.

This is an outstanding project, super light, super fast; kudos! :1st_place_medal: 

I have just downloaded the code, compiled it on my GNU / Debian testing 64-bit system, and my so far experience is the following:

- OK, how do I resize my sidebar?
- Where's the [x] button for the tab window? Meh...`Ctrl+Shift+P` lets me choose the command to close it; that's also an option.
- How do I scroll up or down my window using hotkeys? `Ctrl+UpArrow/DownArrow` do not work.
- Wait...why does it keep on running from inside the terminal? Should not it be like Sublime Text or VSCode that when you run it from inside a directory, it loads that directory and returns back to terminal? I really don't like adding an ampersand at the end of my executable: `./lite &` :unamused: 
- I have opened nearly all C and Lua files and consumes only 0.25% of CPU and 32 MiB of RAM...I mean...DUDE WHAT THE...! :exploding_head: , ~so the real question here is "how do I find out the number of opened tab windows?"~; hmm...you can find the number of opened files by clicking `Ctrl+Shift+P`; not very convenient but it's better than nothing!
- What the hotkey for help command, if any?
- Menu bar?!
- README is not clear how to install a plugin or a theme; I guess I just copy and paste a file in `data/plugins/` for plugins and `data/user/colors/` for theme, respectively? :shrug: 
- What about right-click options?

That's it for now; I will continue with experimentation.

When this editor becomes stable enough, for sure I will switch to it for good; it's exactly what I was looking for!

Keep up the good work mate.

Cheers :+1:

**Comment by stefanos82** [comment]
I have discovered a number of hotkeys and decided to open a new ticket dedicated to them: #65

**Comment by gkeegan** [comment]
You can middle click on an editor tab to close it. You are correct about how to install plugins.

**Comment by stefanos82** [comment]
I have already mentioned it here https://github.com/rxi/lite/issues/65#issuecomment-626318788

**Comment by stefanos82** [comment]
>  * Wait...why does it keep on running from inside the terminal?
> Should not it be like Sublime Text or VSCode that when you run it from 
> inside a directory, it loads that directory and returns back to terminal?
> I really don't like adding an ampersand at the end of 
> my executable: `./lite &` unamused
> 
For this I have found a workaround on my GNU / Debian system.

I have created a script with the following command:
```txt
#!/bin/sh

(/PortableApps/lite/lite & >/dev/null &)
```
I named it `lite.sh` and symlinked it in my `$HOME/bin` directory.

Now I can simply type `lite` in any location of my choice and can continue working on my terminal if I want to.

> * README is not clear how to install a plugin or a theme;
> I guess I just copy and paste a file in `data/plugins/` for plugins
> and `data/user/colors/` for theme, respectively? shrug
> 

We just copy the plugins of our choice from https://github.com/rxi/lite-plugins and place them in `data/plugins/` of Lite's directory.

Now, how do we know which is active and which is not?

Simply press `Ctrl+Shift+P` and choose `Core:Open Log`; it should display all the loaded plugins among other information.

About colors, we copy the color theme of our choice from https://github.com/rxi/lite-colors
and place it in `data/user/colors/`.

Then we go to our `data/user/init.lua` and enable the theme of our choice.

I'm a monokai lover so...yeah lol: `require "user.colors.monokai"`
>     * What about right-click options?
> 
> 
> That's it for now; I will continue with experimentation.
> 
> When this editor becomes stable enough, for sure I will switch to it for good; it's exactly what I was looking for!
> 
> Keep up the good work mate.
> 
> Cheers +1
