### ISSUE TITLE
Scrolling upward at the beginning of a file produces empty lines

### ISSUE THREAD

**Issue by gianmichelemariani** [rxi/lite#6]
Not sure it this is wanted behaviour, but scrolling upward (with the mouse wheel) when at the first line, produces infinite empty lines.

I'm on OSX 10.14.6

**Comment by rxi** [comment]
Being able to scroll outside the vertical bounds of the document is intended behaviour.

**Comment by gianmichelemariani** [comment]
Thanks! Never seen this in any other app, so it seemed strange :)

<img width="1842" alt="Screenshot 2020-01-01 at 13 31 28" src="https://user-images.githubusercontent.com/46694168/71641954-a64f7680-2c9b-11ea-9bb7-e8aab7fe3e7e.png">

**Comment by BenStigsen** [comment]
Can I ask how this makes sense? For what purpose would someone want to scroll out of text view?

**Comment by lordadamson** [comment]
@BenStigsen I like to have the things I type in the middle of the screen, that helps me focus I guess. So sometimes when I'm typing at the very beginning or the very end of a file I'd use this feature to get the text into the middle.

**Comment by BenStigsen** [comment]
Ah, that part I can understand. 
But I don't understand why it's possible to scroll out of text view, and then keep going.

**Comment by rxi** [comment]
The same reason it's possible to make a line with nothing but spaces on it -- practically you likely never want to do this, but realistically how much is your ability to do this hindering your user experience. I *can* scroll past the document bounds such that no text is visible, but I've never accidentally done this and ended up confused about where I am; being able to do this has very little consequence.

The consequence of preventing this, though, does require extra code, and with any extra code there is potential for bugs. It would is trivial to change this behaviour but I'm unconvinced it's an actual problem besides it being a little bit "odd".
