### ISSUE TITLE
quick test of lite 1.03

### ISSUE THREAD

**Issue by pznknmtb** [rxi/lite#62]
first impression was good so I spent some time testing lite 1.03 on win10/hidpi

rendering: is OK, but does not use sub pixels

editing: tab size is 2, cannot find out how to change

find: find previous next (F3, shift-F3) does not work for me, missing: highlight all, show total number of matches

file format: opening non utf-8 file shows no error (added this to #27)

long lines: no line wrap function, no horizontal scroll bar

vertial scolling: when scrolling up (with cursor up) top line is incomplete shows only a few pixels. cannot disable soft scrolling.

sidebar: cannot resize (but cursor shows <->), cannot disable

tabs: cannot arrange tabs (e.g. drag and drop), cannot find full path name (e.g. have two "init.lua", who is who?)

large files: opening file with 1.2 mio lines and 40MB: eats cpu and memory, 2GB after scolling to bottom and waiting. (compare with notepad3: opens faster, scrolls faster, consumes 80MB)

**Comment by stefanos82** [comment]
@pznknmtb for more experimentation, please see my ticket #65 

Have fun! :+1:
