### ISSUE TITLE
Files with long lines

### ISSUE THREAD

**Issue by DoctorGester** [rxi/lite#64]
The attached file hangs the editor for ~1 second on open.
If you rename the file to test.lua or test.js it crashes the editor instantly on open.

[test.txt](https://github.com/rxi/lite/files/4605509/test.txt)

**Comment by stefanos82** [comment]
@DoctorGester that's indeed an interesting finding.

With Lua and JavaScript throws `Fatal error in src/rencache.c: exhausted command buffer`, but not for text file(s).

**Comment by rxi** [comment]
This is an issue with how the renderer cache handles very-long strings, it should be trivial to fix once I get around to it.

**Comment by stefanos82** [comment]
Awesome :+1:

**Comment by rxi** [comment]
Both the long loading time and crashing on long lines should be fixed now. Note these included changes to the C side of things and thus a recompile is required; I've attached recompiled binaries to this message:

[lite_master.zip](https://github.com/rxi/lite/files/4627230/lite_master.zip)
