### ISSUE TITLE
Editor hotkeys found so far

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite#65]
The following information might be the product of multiple plugins used from https://github.com/rxi/lite-plugins.

The test took place under an ANSI C demo code.

So far I have detected the following hotkeys, in case you are interested:

- `Ctrl+L` highlights the whole line
- `Ctrl+\` hides the sidebar
- `Ctrl+D` highlights the word under cursor and shows with highlighted border around multiple findings of that word
- `Ctrl+P` it opens a file from a project
- `Ctrl+Shift+P` runs a command
- `Ctrl+Shift-D` duplicates a line
- `Ctrl+Shift+K` deletes line under cursor
- `Shift+RightArrow` highlights character by character and behaves much like `Ctrl-D`
- `Ctrl+O` Opens a file
- `Ctrl+F` Find Text (in current opened file)
- `Ctrl+Shift+F` Find text in entire Project
- `Ctrl+R` Finds something and replaces it
- `Ctrl+J` This is a very interesting command: it deletes the newline from the end of a line; in other words, you have 3 lines, you place your cursor anywhere in your first line and press the hotkey twice. Now you have a single line.
- `Ctrl+G` Go to line
- `Ctrl+S` Save file
- `Ctrl+Shift+S` Save as
- `Ctrl+A` Select all text
- `Ctrl+[` and `Ctrl+]` jumps from code block to code block? :shrug:
- `Ctrl+Shift+[` and `Ctrl+Shift+]` highlights 3-ish lines forward and backward, respectively 
- `Ctrl+'` Converts all your text to a single, minified line with escaped characters and newlines
- `Ctrl+/` comments the current line; to select multiple lines, press `Ctrl+Shift` and your arrows to select the lines you want, then the aforementioned command.
- `Ctrl+Arrows` Moves the line up or down
- `Ctrl+Shift+Q` it adds a number sign, a hashtag, a pound sign..?, name it however you like, and makes a code block as a single line; weird behavior
- `Alt+Shift+L` clones the current screen on your right, vertically while maintaining curret's position on the cloned file; press `Ctrl+W` to close it
- `Alt+Shift+K` clones the current screen on the bottom, horizontally while maintaining curret's position on the cloned file; press `Ctrl+W` to close it
- `Alt+Shift+J` clones the current screen on your right, vertically while maintaining curret's position on the *opened* file; press `Ctrl+W` to close it

**Comment by stefanos82** [comment]
Update: seems like mouse's middle key (scroll) closes tab windows as well.

**Comment by stefanos82** [comment]
To arrange your tabs, use `Ctrl+PageUp` and `Ctrl+PageDown`.

**Comment by dnlo** [comment]
@stefanos82 
You can find some more here https://github.com/rxi/lite/blob/master/data/core/keymap.lua

**Comment by stefanos82** [comment]
lol @dnlo you so right :facepalm: how come I thought it was part of the C code instead of of Lua?

Thanks a million mate :100:

**Comment by ghost** [comment]
Does this text editor have the shortcut key to use multiple cursor at once? Like in VScode, ctrl+d or f2?

**Comment by ChildishGiant** [comment]
>Does this text editor have the shortcut key to use multiple cursor at once 

Lite XL supports multi-cursor as of 2.0.0
