### ISSUE TITLE
How to prevent directory loading when first run

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite#66]
Whenever I open Lite from run command on my XFCE4 system, it opens and immediately starts file loading procedure which makes no sense to me.

1) How do I prevent this?
2) How to open a directory of my choice, much like we do with Sublime Text and VSCode?

**Comment by rxi** [comment]
See #57

**Comment by stefanos82** [comment]
Hmm...that doesn't make any logical sense to me. :thinking: 

In other words, if I'm on a Windows machine and have a 10TB hard drive that contains countless of parse-able data, does it mean Lite will attempt to load the entire `C:\` drive?

That would take ages to load!

Not all users know how to use a terminal or a command prompt @rxi in order to tell the editor "hey, load this directory please".
