### ISSUE TITLE
keymap: use command instead of control on macOS

### ISSUE THREAD

**Issue by zmb3** [rxi/lite#67]
Hi there - awesome project!

On macOS, the command key is generally the default modifier instead of control.  I'd be happy to work on this with a little guidance as I'm not too familiar with Lua.  I'm not sure if there's a way to detect if we're on mac at compile time or if runtime checks will be necessary.

**Comment by rxi** [comment]
See the [`macmodkeys`](https://github.com/rxi/lite-plugins/blob/master/plugins/macmodkeys.lua) plugin -- this remaps command/option to control/alt
