### ISSUE TITLE
Compiling in macOS

### ISSUE THREAD

**Issue by abdurrahmanarikan** [rxi/lite#68]
Hi 
thanks for the open source project,
I am trying to run it on my mac. I am able to compile it but when I run it, it opens as zoomed window
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/24858031/81500765-f343f900-92dc-11ea-86cb-de2b7fff3eac.png">
Can you help ?

**Comment by rxi** [comment]
See #46
