### ISSUE TITLE
Question: Is LSP supported, or will it be?

### ISSUE THREAD

**Issue by ell1e** [rxi/lite#75]
If I may ask since I couldn't tell from the README or from poking around in the source: is it possible to pick external [language servers](https://langserver.org/) to provide basic error annotation and possibly auto completion? The language server protocol (=LSP) folks also appear to be in the process of adding in syntax highlighting, [which they call "semantic highlighting"](https://github.com/microsoft/language-server-protocol/issues/18), which would then allow lite users to just plug in an LSP to get highlighting  for *any* language, even if usually unsupported by lite. (While Visual Studio Code, Atom, and other "big" editors often have plugins for tweaking details of a given language on top of LSP, this appears to be unnecessary since e.g. KDE's kate allows just picking any language server binary without a kate-specific plugin for the respective language.)

I understand if for a light-weight text editor LSP is too bloated. However, it might also be one of the most lightweight ways to get more advanced features (like smarter auto completion) with almost zero complex language-specific handling code inside the lite codebase, so maybe it'd be worth looking at.

**Comment by zmb3** [comment]
Also interested in this. Since most LSP features need some sort of display, it would be really cool if there was one plugin that implemented the UI elements required, and other language specific plugins could simply be the bridge between an external language server and the UI package.

**Comment by ell1e** [comment]
Curious, why would you even want a language-specific plugin? Other than optionally, for if you want the convenience of the LSP server automatically downloaded or 1-2 additional settings for convenience the protocol can't provide (like tab vs spaces), I thought the point of LSP kind of is that you don't need one.

**Comment by gingerBill** [comment]
I don't see any need for the text editor itself to need support for the "language server protocol". This "feature" can be added purely as a plugin like everything else.

**Comment by rxi** [comment]
This is not something I have plans of looking into myself, but anyone is welcome to work out if it's possible to do using `lite`'s plugin system, and if so try their hand at writing such a plugin, or otherwise make an issue outlining what would prevent such a plugin from being possible.

**Comment by ell1e** [comment]
Ok thanks for the update, in that case I might as well close this
