### ISSUE TITLE
 Opening a new tab in an existing instance from the command line

### ISSUE THREAD

**Issue by josepsanzcamp** [rxi/lite#76]
Hi team.

First: I want to congratulate you by this lightweight editor, it's a really quick editor.

Second: It's posible to open a file in a new tab of an existing instance from the command line??? It's an important feature for me because I live in the terminal!!!

Thanks in advance by your great work!!!

Josep.

**Comment by harikt** [comment]
I don't think that particular feature will work. 

If you have already opened the lite. But there is another way / work around. Install the console plugin. Now you can list the files in the particular directory and the files are clickable. 

Hope that helps :-) .

**Comment by rxi** [comment]
Thanks for the kind words @josepsanzcamp -- This isn't a feature I currently plan to support in lite, though you could add the functionality in a rudimentary way by having a plugin which periodically checks a file to see if it exists and loads the filename from that file if it does; you could then pair this with a simple shell script which creates the file from its arguments.

**Comment by vredesbyyrd** [comment]
@rxi 

I did not think it appropriate to open a new issue for this question.  Atom is my current daily driver, but its overkill for my needs, also very sluggish. Lite is a beautiful and quick editor, thank you for your work and sharing it! 

I often open files with a `gosearch` front-end of mine.

![Screenshot from 2020-06-23 18-33-54](https://user-images.githubusercontent.com/22080838/85477633-52558880-b580-11ea-9541-ebd6be424474.png)

Currently it just uses `xdg-open` to open the selected filepath,  atom handles opening the file in a new tab of an existing instance. 

> This isn't a feature I currently plan to support in lite, though you could add the functionality in a rudimentary way by having a plugin which periodically checks a file to see if it exists and loads the filename from that file if it does; you could then pair this with a simple shell script which creates the file from its arguments.

I am trying to envision how to implement a plugin that accomplishes something along these lines. Any more hints or parts of lites source I should be looking at? Perhaps having my search tool write the selected filepath to a fifo or file, and a plugin that watches for said fifo/file would be sufficient? 

I'm loving your editor and would love even more to jump ship! Thanks for your time.
