### ISSUE TITLE
Feature suggestion: minimal toolbar for better touch device use & beginner friendliness (mockup included)

### ISSUE THREAD

**Issue by ell1e** [rxi/lite#78]
I really like the concept of using this editor! I had this idea for a tiny change to make it even more approachable and touch device friendly (imagine firing up lite on a windows 10 tablet and you forgot your bluetooth keyboard and you just want to do a 1-2 letters edit, and now inputting CTRL+SHIFT+P or CTRL+S might be more involved):

![toolbar](https://user-images.githubusercontent.com/64124388/81531704-7f006880-9363-11ea-92ba-216420c472df.png)

This small toolbar would just provide two shortcuts to trigger the given two commands I annotated. Clicking a button would do exactly what entering that command with the keyboard does, so the file browser at the bottom would otherwise remain working as before. (One day maybe a preferences button could be a worthwhile third icon to add.) This toolbar could be enough to get anyone completely unfamiliar with the editor started, and with everything else remaining as-is, including the cool helpful `CTRL+SHIFT+P` hint text in the every center at launch, people will still be strongly incentivized to get used to the usually quicker keyboard command style.

**Comment by rxi** [comment]
This isn't something I'd want in the core of lite, but the the plugin system *does* allow for this functionality to be implemented as a plugin. See the `treeview` plugin in `data/core` for how to go about achieving this by creating a custom locked "view" if it's something you're interested in implementing yourself.

**Comment by ell1e** [comment]
That's a shame, I think it'd go a long way towards making the first few minutes a bit more intuitive. But the configurability is certainly appreciated.
