### ISSUE TITLE
Reloading Plugins: command.add() crashes script

### ISSUE THREAD

**Issue by doczi-dominik** [rxi/lite#79]
Hello, I really like this project so far and I am developing / editing plugins for lite. The only pain point is that I have to re-launch lite after every change to test the plugin. Using `Core: Reload Module` does not help, because many plugins contain either `command.add()` (or possibly other similar functions) which causes the script to crash, which does not get loaded AND in turn causes it to not show up in the Reload Module menu.

Is there a way to handle this gracefully? Logging these events are useful even if they are intentional, but I don't believe they should crash the entire script.

Awaiting response, thank you in advance!

**Comment by rxi** [comment]
I wasn't planning to change this behaviour; the `reload module` command was initially added for when I was writing the colour themes and is useful for quickly changing colour themes or reloading *basic* configuration, it wasn't really intended for reloading plugins (though can be useful for loading a plugin for the first time without restarting).

To avoid the error in your specific scenario, you can first unset the command in `command.map`, (eg. `command.map["doc:save"] = nil`) and *then* use `command.add()`. Typically I've found having a second instance of the editor which I'm restarting as I work on a plugin is an acceptable enough workflow, especially given the focus on having lite be able to close and open quickly.

**Comment by doczi-dominik** [comment]
Okay, I understand. Thank you for the tip! I use a tiling WM on a small 1366x768 screen, so it's a bit difficult for me to view windows side-by-side or to switch to another workspace, not to mention leaving a terminal window open for `lite` to use the correct working dir.

That is a personal problem though, - at least the implications of `reload module` are clear to me now - once again thank you for your response!
