### ISSUE TITLE
Crash on alt-tab

### ISSUE THREAD

**Issue by petrihakkinen** [rxi/lite#85]
I'm getting a crash consistently when alt-tabbing away from lite on Windows.

Error: C:\lite-dev\lite/data/core/init.lua:351: attempt to call field 'wait_event' (a nil value)
stack traceback:
	C:\lite-dev\lite/data/core/init.lua:351: in function 'step'
	C:\lite-dev\lite/data/core/init.lua:417: in function 'run'
	[string "local core..."]:9: in function <[string "local core..."]:2>
	[C]: in function 'xpcall'
	[string "local core..."]:2: in main chunk

**Comment by petrihakkinen** [comment]
Sorry, never mind. My executable and Lua files were out of sync.

**Comment by rxi** [comment]
Not a problem! I've attached a windows build from the master branch if you want to continue running the master-branch lua without having to wait for the next release.

[lite_master.zip](https://github.com/rxi/lite/files/4611760/lite_master.zip)

**Comment by petrihakkinen** [comment]
Thanks!
