### ISSUE TITLE
Editor not recognizing commenting trick ---[[ --]]

### ISSUE THREAD

**Issue by yir0n** [rxi/lite#86]
When you write comments both using -- or --[[ ]] everything works fine, but if you do the trick of using double dashes before closing the double brackets and add another dash to the beginning, it keeps commented out.

Example:
```
---[[
function fact (n)
  if n < 0 then
   print("Cannot factorialize negative numbers!")
  elseif n == 0 then
    return 1
  else
    return n * fact(n - 1)
  end
end

print("enter a number:")
a = io.read("*n")        -- reads a number
print(fact(a)) --]]
```

This is not a comment, but stays grey in the editor:
![image](https://user-images.githubusercontent.com/42983358/81623108-1055f600-93c9-11ea-8f6d-9e69e74cdd7f.png)

**Comment by SimpleBinary** [comment]
@yir0n I noticed this too, it seems to be a problem with how it detects Lua's syntax, found in `./data/plugins/language_lua.lua`:

```lua
...
{ pattern = { "--%[%[", "%]%]"},      type = "comment"  },
...
```

It sees the **correct pattern** because there is no exception when the line begins with `---` instead of `--`.

**Comment by rxi** [comment]
@SimpleBinary The `--%[%[` pattern was broken, due to missing the escape characters (`%`) the first part of the pattern (`--`) was matching a single `-` followed by any-number-of `-`, as opposed to one `-` followed by another `-`. Should work as expected now!
