### ISSUE TITLE
'SDL2/SDL.h' file not found

### ISSUE THREAD

**Issue by specter78** [rxi/lite#88]
I am getting this error while trying to compile on macOS.

Another error:

```
warning: 'tmpnam' is deprecated: This function is
provided for compatibility reasons only. Due to security concerns inherent
in the design of tmpnam(3), it is highly recommended that you use
mkstemp(3) instead.
```

**Comment by joaoventura** [comment]
Maybe `brew install sdl2` solves it... Didn't try..

**Comment by specter78** [comment]
> Maybe `brew install sdl2` solves it... Didn't try..

Thanks. That worked. 

Though I do not understand why a text editor needs a low level api to interact with hardware.
