### ISSUE TITLE
File Closing, No Settings.json? or Something Similiar? 

### ISSUE THREAD

**Issue by dephraiim** [rxi/lite#92]
Is it me or I just cannot close the file after I use it and as lite as it is, It is very confusing.
How do I activate the new Color Plugins? Because they are not showing and I cannot see any option for it.
I want to use a custom font. How? There is no option.

Is there a shortcut key I am missing?

**Comment by jack1243star** [comment]
- Middle mouse button (or wheel click) on the tab to close it.
- Take a look at `data/user/init.lua` for setting the font. The defaults are in `data/core/style.lua`.
- The settings can also be accessed via `Ctrl+Shift+P`, then type `user`.

For example, here is my setting for the font: 
```lua
style.code_font = renderer.font.load("D:/CozetteVector.ttf", 12)
```

- There are other things that can be tweaked, such as `treeview_size` in `core.config` for sidebar width.
- You should put the color files in `data/user/colors`.
- There's not much documentation unfortunately (or have I missed them?), but most things can be figured out in the `lua` source code, which is fairly readable.

Honestly your problem does not warrant opening an issue, but the documentation situation could be improved.

**Comment by dephraiim** [comment]
Thank You. It's much helpful. I just love it because of it lightness.
