### ISSUE TITLE
Change the command line behaviour to executing then exiting

### ISSUE THREAD

**Issue by Daaniiieel** [rxi/lite#95]
This isn't a traditional issue, but rather a recommendation. Many text editors like sublime and VS Code do this by default. When the user opens a file in the terminal, they exit (the process doesn't occupy the terminal).
This behavior can be achieved with 
```lite &```
```disown```
currently. 
Can the community consider doing this?

EDIT: example: https://file.coffee/u/O70l0-Pyr5s.mp4

 <video width="320" height="240" controls>
  <source src="https://file.coffee/u/O70l0-Pyr5s.mp4" type="video/mp4">

</video>

**Comment by rxi** [comment]
I'm opposed to changing this, I don't see any clear or obvious advantage to it given the same behaviour can be achieved by appending `&` as you pointed out, additionally one could write a simple bash script to avoid having to write the `&` at all.

In terms of downsides this would make the behaviour of `lite` non-standard compared to most software, it would also prevent it from being used as an editor for git commit messages.

**Comment by stefanos82** [comment]
@Daaniiieel I'm sure many VSCode and Sublime Text users would want this feature in Lite as well.

Personally, I have imitated this behavior on my Debian system by creating a shell script with the following code:
```sh
#!/bin/sh

(/PortableApps/lite/lite & >/dev/null &)
```
I would love this behavior to be part of the executable though...

**Comment by Daaniiieel** [comment]
I will close this. It's clear that lite wants to be minimalist and, the git commit issue is really there.
Maybe a lite fork with IDE like features like this? :)

**Comment by stefanos82** [comment]
@Daaniiieel there are a few things I don't like either, but time will tell whether a fork should worth the effort or not.

I have a feeling a fork will appear one day...
