### ISSUE TITLE
Add a roadmap in README

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite#96]
@rxi based on your personal feedback we read from opened tickets, we can clearly see you have a certain vision of how you want Lite to behave as a whole.

There are lots of things I would want to see in Lite, but clearly you have a different taste than I.

I'm pretty sure the majority of Lite candidate users would want to see a resemblance of Sublime Text and VS Code; you know, the use of their best features combined.

Can you please add a roadmap in README with specific things you plan to add so we can get a rough idea what you want to achieve with Lite?

This way would save you time from answering the same question(s) over and over again, if their gist is more or less the same.

You could simply point them at that document region and tell them "please read 'Foo' part of README", much like an FAQ.

**Comment by rxi** [comment]
I don't have a strict roadmap for lite, it hasn't been developed with the intent of ticking check boxes, but rather through using it, feeling it needs a feature, then adding that feature soon after. 

I feel the both the "overview" and "contributing" sections do a good job of summarising what the goals are for the project:

> it aims to provide something practical, pretty, small and fast, implemented as simply as possible; easy to modify and extend, or to use without doing either.

> Any additional functionality that can be added through a plugin should be done so as a plugin, after which a pull request to the plugins repository can be made. In hopes of remaining lightweight, pull requests adding additional functionality to the core will likely not be merged. Bug reports and bug fixes are welcome.
