### ISSUE TITLE
Window flashes when opening lite

### ISSUE THREAD

**Issue by miere43** [rxi/lite#97]
Version: lite 1.03
OS: Windows 10 x64

When you open lite for the first time, you can see window opening with white background.

![Annotation 2020-05-14 233625](https://user-images.githubusercontent.com/3995549/81984222-2a980a00-963d-11ea-98f3-f299ace10567.png)

If you have dark theme installed in lite, its very annoying when window flashes with white color and then instantly renders a frame with dark theme. Is it possible to render first frame and only then show window? I know its possible when rendering with DirectX 11, calling Present on swap chain and then showing window, but I don't know if it is possible with SDL.

I can take a look at this myself if you are okay with my proposed solution.

**Comment by rxi** [comment]
Would you be able to let me know whether this fixes the issue for you, if so I'll push a commit:

[lite.zip](https://github.com/rxi/lite/files/4630979/lite.zip)

**Comment by miere43** [comment]
@rxi Yes, it works. Thank you!
