### ISSUE TITLE
Simple UX improvements for Markdown

### ISSUE THREAD

**Issue by mythz** [rxi/lite#99]
First off I just wanted to say I love lite! it's super light/fast with built-in tree-view + syntax highlighting in a beautiful dark mode by default.

I love its minimal style which I'm now using as a minimalist distraction-free editor for writing Markdown docs.

However there's a few simple quick wins I think would greatly improve its UX for Markdown when text is selected:

 - `*,_` - emphasize selected text (nice2have: be able to press `*` twice for `**bold**`)
 - **`,",'** - quote selected text
 - `[` - put brackets around selected text
 - `(` - put parens around selected text

The other nice to have is "word wrap" but I'm assuming it's harder to implement with lite's architecture otherwise it would likely exist already.

Anyway just wanted to submit this feature request somewhere for IMO one if its popular use-cases in writing docs, thx to its gorgeous minimalist style.

**Comment by rxi** [comment]
Thanks for the kind words! You're right about word wrap -- this is likely not a feature that will be added.

Regarding the selection-based-inserts, this would be a great candidate for a plugin and would be trivial to achieve using the `doc:has_selection()` in the predicate of `command.add()`, then `doc:replace()` in the commands -- the plugin could then simply bind the keys `"`, `[` etc. in the keymap to the the commands. If you write such a plugin a pull request to the `lite-plugins` repo would be welcome!
